# Visual Odometry
## Done by: Projit and Abhinav 
(Abhinav wrote the function implementing 8-point algorithm and Projit worked on the RANSAC loop and scaling. Both worked on the updates in the main loop.)

We calculate the trajectory of the vehicle, using a basic monocular visual odometry algorithm. 

Importing libraries

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import numpy.linalg as linalg
import random

A bunch of utility functions to help us through the way:

In [2]:
# Utility Functions

def display_image(img):
    img2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img2)
    plt.show()

def draw_line(img, A, B):
    cv2.line(img, A, B, (0, 255, 0), thickness=3, lineType=8)

def add_column(original, newcol):
    return np.concatenate([original, newcol], axis=1)

def add_row(original, newrow): # didn't use
    return np.concatenate([original, newrow], axis=0)

def draw_point(image, point, color):
    if color == "green":
        cv2.circle(image, point, 10, (0, 255, 0), thickness=3, lineType=8)
    elif color == "red":
        cv2.circle(image, point, 8, (0, 0, 255), thickness=3, lineType=8)


## Finding Matches
Given the keypoints and descriptors, we want to find corresponding features between two frames. So we use Lowe's ratio test to find the good matches. Matches are done using a brute force KNN. 0.15 is the hyperparameter we choose to ensure that we don't have matches in the same area of the image.  

In [3]:
# Finding matches
bf = cv2.BFMatcher()
def find_matches(des1, des2, kp1, kp2):
    matches = bf.knnMatch(des1, des2, k=2)
    good = []
    for m in matches:
        if m[0].distance < 0.15*m[1].distance:
            good.append(m)
    if len(good) > 10:
        matches = np.asarray(good)
    else:
        matches = np.asarray(matches)
    if len(matches[:,0]) >= 8:
        src = np.float32([ kp1[m.queryIdx].pt for m in matches[:,0] ]).reshape(-1,1,2)
        dst = np.float32([ kp2[m.trainIdx].pt for m in matches[:,0] ]).reshape(-1,1,2)
    src_new = []
    dst_new = []
    for i in range(len(src)):
        src_new.append(src[i][0])
        dst_new.append(dst[i][0])
    return src_new, dst_new


## Computing the Fundamental Matrix
We use the 8-point algorithm to compute the fundamental matrix. We take the 8 points in A and then find the eigenvectors and select based on the eigenvalue. Here is a function that does this: 

In [4]:
# Check somewhere here that at least 
def compute_fundamental(src, dst):
    A = np.array([
    [src[0][0]*dst[0][0], src[0][0]*dst[0][1], src[0][0], src[0][1]*dst[0][0], src[0][1]*dst[0][1], src[0][1], dst[0][0], dst[0][1], 1],
    [src[1][0]*dst[1][0], src[1][0]*dst[1][1], src[1][0], src[1][1]*dst[1][0], src[1][1]*dst[1][1], src[1][1], dst[1][0], dst[1][1], 1],
    [src[2][0]*dst[2][0], src[2][0]*dst[2][1], src[2][0], src[2][1]*dst[2][0], src[2][1]*dst[2][1], src[2][1], dst[2][0], dst[2][1], 1],
    [src[3][0]*dst[3][0], src[3][0]*dst[3][1], src[3][0], src[3][1]*dst[3][0], src[3][1]*dst[3][1], src[3][1], dst[3][0], dst[3][1], 1],
    [src[4][0]*dst[4][0], src[4][0]*dst[4][1], src[4][0], src[4][1]*dst[4][0], src[4][1]*dst[4][1], src[4][1], dst[4][0], dst[4][1], 1],
    [src[5][0]*dst[5][0], src[5][0]*dst[5][1], src[5][0], src[5][1]*dst[5][0], src[5][1]*dst[5][1], src[5][1], dst[5][0], dst[5][1], 1],
    [src[6][0]*dst[6][0], src[6][0]*dst[6][1], src[6][0], src[6][1]*dst[6][0], src[6][1]*dst[6][1], src[6][1], dst[6][0], dst[6][1], 1],
    [src[7][0]*dst[7][0], src[7][0]*dst[7][1], src[7][0], src[7][1]*dst[7][0], src[7][1]*dst[7][1], src[7][1], dst[7][0], dst[7][1], 1],
    ])
    B = np.matmul(A.transpose(), A)
    eigenValues, eigenVectors = linalg.eig(B)
    idx = eigenValues.argsort()[::-1]   
    eigenValues = eigenValues[idx]
    eigenVectors = eigenVectors[:,idx]
    temp = eigenVectors[1]
    #temp = eigenVectors[-1]
    F = np.array([
        [temp[0], temp[1], temp[2]],
        [temp[3], temp[4], temp[5]],
        [temp[6], temp[7], temp[8]]
    ])
    return np.real(F)

## RANSAC
We have a bunch of matches with us. Now we want to calculate a fundamental matrix and evaluate how accurate it is on these points. So we randomly select 8 points, calculate F, and see how close x' F x gets to zero. That is, our metric is to minimize x' F x = 0. Closer to 0 would imply a better F matrix

In [5]:
# RANSAC loop
def RANSAC_LOOP(src, dst):
    RANSAC_TIMES = 800
    num_vals = len(src)
    minval = 9999999
    F_hold = None
    for i in range(RANSAC_TIMES):
        # Choose random 8.
        rand_choice = [random.randint(0, num_vals-1) for x in range(8)]
        src_input = [src[x] for x in rand_choice]
        dst_input = [dst[x] for x in rand_choice]
        F_temp = compute_fundamental(src_input, dst_input)
        tot = 0
        for j in range(num_vals):
            vec1 = np.transpose(np.array([dst[j][0], dst[j][1], 1]))
            vec2 = np.array([src[j][0], src[j][1], 1])
            temp2 = np.matmul(vec1, F_temp)
            tot += np.matmul(temp2, vec2)
        if tot < 0:
            tot = -1 * tot
        if tot < minval:
            F_hold = F_temp
            minval = tot
    print(minval)
    return F_hold

## Loading the dataset
We load the KITTI datset and we extract SIFT kepypoints and descriptions from all the images. 

In [6]:
# Setup, run this only once.
K = np.array([[7.215377000000e+02,0.000000000000e+00,6.095593000000e+02],
              [0.000000000000e+00,7.215377000000e+02,1.728540000000e+02],
              [0.000000000000e+00,0.000000000000e+00,1.000000000000e+00]])

# Loading all the images.
dir_im = os.listdir('./images')
dir_im.sort()
images = [cv2.imread(os.path.join('./images', x)) for x in dir_im]

# Extracting all the sift features from each of the images.
features = []
sift = cv2.xfeatures2d.SIFT_create()

for im in images:
    kp1, des1 = sift.detectAndCompute(cv2.cvtColor(im, cv2.COLOR_BGR2GRAY), None)
    features.append({"kp": kp1, "des": des1})
    

FileNotFoundError: [Errno 2] No such file or directory: './images'

## Scaling
This function computes the norm between the ground truth and our predicted vector. We use this as a sacaling factor. 

In [7]:
def get_absolute_scale(pose_c, index):
    pose = pose_c[index - 1].strip().split()
    x_prev = float(pose[3])
    y_prev = float(pose[7])
    z_prev = float(pose[11])
    pose = pose_c[index].strip().split()
    x = float(pose[3])
    y = float(pose[7])
    z = float(pose[11])

    true_vect = np.array([[x], [y], [z]])
    prev_vect = np.array([[x_prev], [y_prev], [z_prev]])

    return np.linalg.norm(true_vect - prev_vect)

## The main loop
- First, for every pair of image frames, we find the matches.
- Then we run RANSAC to estimate the fundamental matrix between the two images. We get the best fundamental matrix from this. 
- We then calculate the eseential matrix from the fundamental one by K<sup>T</sup>FK
- Then, we recover R and t from `cv2.recoverPose`
- Then we compose the previous rotations and translations to create the current position by:
`t_old = t_old + np.linalg.inv(R).dot(t) * abs_scale `
- We then update R by `R_old = R.dot(R_old)`
- Concatenating R and t and we print it onto the results file. 


In [44]:
def main():
    strf = ''

    R_old = np.eye(3); # np.zeros((3, 3))
    t_old = np.zeros((3, 1))
    P = add_column(R_old, t_old)
    P = add_row(P, np.array([[0, 0, 0, 1]]))
    with open('./ground-truth.txt') as f:
        pose_c = f.readlines()

    #for i in range(1, 100:
    for i in range(1, len(images)):
        src, dst = find_matches(features[i-1]['des'], features[i]['des'], features[i-1]['kp'], features[i]['kp'])
        src = np.array(src)
        dst = np.array(dst)
        F = RANSAC_LOOP(src, dst)
        E = np.matmul(np.matmul(K.T, F), K)
        print('E:', E)
        print('F:', F)
        _, R, t, mask = cv2.recoverPose(E, src, dst)
        
        if i <= 2:
            R_old = R
            abs_scale = get_absolute_scale(pose_c, i)
            t_old = t * abs_scale

        else:
            abs_scale = get_absolute_scale(pose_c, i)
            t_old = t_old + np.linalg.inv(R).dot(t) * abs_scale 
            R_old = R.dot(R_old)
            
        print("abs scale: %2.4f | progress: %d | len(src): %d " %(abs_scale, i, len(src)))
        # print(P.shape)
        for x in add_column(R_old, t_old):
            for y in x:
                strf += str("{:.6e}".format(float(y))) + ' '
        strf = strf[:-1]
        strf += '\n'
    f = open('results.txt', 'w')
    f.write(strf)

In [47]:
main()

351.01970400115533
En: [[-7.39538648e-06 -9.97665727e-04  2.61985817e-01]
 [ 9.91938811e-04  4.47658086e-06 -6.56781880e-01]
 [-2.56859951e-01  6.58803446e-01  1.25851471e-05]]
E: [[-109619.49438706  340631.70187381  -10893.05046957]
 [ 132357.10036733  344927.0439312   194437.57751987]
 [ -60898.27600497  370400.309089     37378.63913497]]
Fn: [[-5.10402448e-07 -5.40860314e-04  9.42532131e-02]
 [ 5.40653141e-04  2.94106363e-07 -3.31403291e-01]
 [-9.54304676e-02  3.30979563e-01  1.00000000e+00]]
F: [[-2.10557027e-01  6.54285068e-01  1.54208451e-01]
 [ 2.54231400e-01  6.62535557e-01 -1.43641667e-02]
 [ 1.39456823e-03  1.04894008e-03  4.45591674e-04]]
abs scale: 0.9619 | progress: 1 | len(src): 68 
6054.2386650859335
En: [[ 1.20796151e-06 -1.13171313e-03  1.48338590e-01]
 [ 1.12804906e-03  8.37885852e-06 -6.91371381e-01]
 [-1.48810862e-01  6.91269882e-01  8.04311329e-06]]
E: [[-113088.61565502  332219.71395357  -16116.47302587]
 [ 267774.21549556 -248413.70708656  166693.55532304]
 [ -31

29954.03683105283
En: [[ 2.10476280e-07 -1.09945073e-03  1.92201774e-01]
 [ 1.09871661e-03  4.98327574e-06 -6.80483114e-01]
 [-1.92431711e-01  6.80418129e-01  4.45097297e-06]]
E: [[-123838.16658824  326034.01864286  -26689.25118547]
 [ 313334.50968347 -187364.98801325  219814.19918952]
 [ -29554.71571113  230550.25054589   30113.19889628]]
Fn: [[ 9.25714402e-07  8.51167848e-03 -1.49026589e+00]
 [-8.50762919e-03  2.94616648e-07  5.22378154e+00]
 [ 1.49005370e+00 -5.23328286e+00  1.00000000e+00]]
F: [[-2.37868239e-01  6.26245851e-01 -2.43709136e-01]
 [ 6.01852646e-01 -3.59890501e-01 -9.49842823e-03]
 [ 1.42370325e-03  8.00917942e-04 -1.51786954e-04]]
abs scale: 0.8842 | progress: 13 | len(src): 54 
2993.472381294385
En: [[-1.68087352e-06 -1.11167862e-03  1.91597502e-01]
 [ 1.11120486e-03  2.50270418e-06 -6.80653480e-01]
 [-1.90679655e-01  6.80911180e-01  3.81879189e-06]]
E: [[-104471.50547487  343424.69010454   -5856.34290066]
 [  60660.80822644  360177.25986068  137531.11709591]
 [ -737

7400.536668865549
En: [[ 7.14993422e-07 -1.01851731e-03  1.45155288e-01]
 [ 1.02478275e-03 -3.76416016e-06 -6.92046887e-01]
 [-1.46366533e-01  6.91791730e-01 -6.62609960e-06]]
E: [[-110239.93438992  332105.44179204  -13742.41943304]
 [ 250656.59597885 -265283.77396229  148217.76454667]
 [ -33082.17956196  217012.40512246   23898.75045081]]
Fn: [[ 4.22238887e-07  3.77052011e-03 -6.62909621e-01]
 [-3.77411011e-03  3.61245648e-06  2.29807947e+00]
 [ 6.62059152e-01 -2.30016165e+00  1.00000000e+00]]
F: [[-2.11748767e-01  6.37907835e-01 -2.37507783e-01]
 [ 4.81460965e-01 -5.09556835e-01  1.92218388e-02]
 [ 1.42570413e-03  6.24318514e-05  9.56782386e-04]]
abs scale: 0.8632 | progress: 25 | len(src): 71 
61262.867807710805
En: [[ 2.68353706e-06 -1.12289213e-03  1.84236361e-01]
 [ 1.12541427e-03 -8.18688839e-07 -6.82682722e-01]
 [-1.86106585e-01  6.82175253e-01 -4.29673933e-06]]
E: [[-145959.45860379  316088.37905664  -47428.87208834]
 [ 366851.72344842   51688.17913739  322305.40740645]
 [ -35

110149.2743474374
En: [[ 1.96613390e-06 -1.21285301e-03  2.61948263e-01]
 [ 1.21322784e-03  2.38848022e-06 -6.56796494e-01]
 [-2.63113892e-01  6.56330411e-01  4.74730803e-08]]
E: [[-119256.5259508   321115.46783577  -23644.69477937]
 [ 332454.37103036 -164120.64038443  241550.78474418]
 [ -21105.48938748  231963.38635009   37891.00337802]]
Fn: [[-6.76069093e-07  1.06700152e-03 -1.86842784e-01]
 [-1.06756636e-03 -1.95092688e-07  6.43765230e-01]
 [ 1.86009614e-01 -6.44825173e-01  1.00000000e+00]]
F: [[-2.29067828e-01  6.16798303e-01  2.44503730e-01]
 [ 6.38578058e-01 -3.15242779e-01  1.20110321e-02]
 [-1.05575012e-03  6.10144001e-04 -1.07010909e-04]]
abs scale: 0.7446 | progress: 37 | len(src): 73 
16505.196918801827
En: [[ 1.45729914e-06 -1.05391353e-03  1.68829963e-01]
 [ 1.06126292e-03 -4.40870686e-06 -6.86655169e-01]
 [-1.70668041e-01  6.86200630e-01 -8.61532389e-06]]
E: [[-95860.33633425 343028.19087319    978.52977554]
 [332045.80691645 -99218.98357406 256746.38994182]
 [ -1436.575

388903.14528055687
En: [[ 1.19929890e-05  2.17942268e-03 -4.99953823e-01]
 [-2.16291721e-03  9.39044718e-05  5.00041633e-01]
 [ 4.85935089e-01 -5.13675181e-01 -1.42196442e-05]]
E: [[  76765.38371912 -351803.86016121  -19927.73468484]
 [ -52566.97618617  -91177.17490213  -66250.60821292]
 [  52254.02243428 -319050.31679647  -32710.65173501]]
Fn: [[ 1.98462491e-06  4.30225873e-04 -7.66355537e-02]
 [-4.29791995e-04  2.38279046e-06  2.40951747e-01]
 [ 7.34243744e-02 -2.40602757e-01  1.00000000e+00]]
F: [[ 1.47450880e-01 -6.75744540e-01 -6.93333509e-01]
 [-1.00970601e-01 -1.75133036e-01  1.37745141e-03]
 [-6.51976725e-03 -2.26200582e-03 -1.91591421e-04]]
abs scale: 0.6501 | progress: 49 | len(src): 139 
334558.2434750606
En: [[ 6.85549548e-06  1.87642792e-03 -4.49285529e-01]
 [-1.85663962e-03  5.78332163e-05  5.46021180e-01]
 [ 4.38489431e-01 -5.54728251e-01 -8.54369389e-06]]
E: [[ 119534.95498429 -282649.25639672   33553.80009256]
 [-358449.05389966   17470.90220808 -298746.32902529]
 [  1

36486.6004418543
En: [[ 5.63722045e-07 -1.03392644e-03  2.21139767e-01]
 [ 1.02195073e-03  6.98169555e-06 -6.71636920e-01]
 [-2.19597685e-01  6.72142689e-01  1.22639643e-05]]
E: [[ -91893.76860674  350389.519009      6163.59272488]
 [ 258959.62912412 -248283.69399512  159269.1118439 ]
 [ -15594.78766404  236530.65671044   43362.20501565]]
Fn: [[ 1.36524422e-06 -1.83501052e-03  3.15883364e-01]
 [ 1.83513221e-03 -8.69968662e-07 -1.11025379e+00]
 [-3.15239219e-01  1.09938194e+00  1.00000000e+00]]
F: [[-1.76509468e-01  6.73027874e-01 -2.00270455e-01]
 [ 4.97409424e-01 -4.76903097e-01 -3.02563784e-02]
 [ 5.11529106e-04 -1.10305786e-03 -8.06934675e-05]]
abs scale: 0.3976 | progress: 61 | len(src): 187 
269320.758901189
En: [[-5.15111904e-04 -6.12622144e-02  2.39199319e-01]
 [ 6.28109836e-02 -1.69338976e-03 -6.62498028e-01]
 [ 2.37379031e-01 -6.63193971e-01  1.89468733e-03]]
E: [[-118002.2622001   332598.95383593  -19863.78308712]
 [ 337571.47584149  145145.71354451  319976.69010633]
 [ -1882

185833.265893443
En: [[ 2.99689294e-07 -8.47455761e-04  8.69508232e-02]
 [ 8.36429399e-04 -1.28402572e-05 -7.01739878e-01]
 [-8.59218738e-02  7.01866591e-01 -1.00717595e-05]]
E: [[ -27530.07787082  366007.58548459   64360.65263292]
 [-244538.46355248  272101.32778822 -141426.33492193]
 [ -81850.60250015  374390.90870808   20482.76616706]]
Fn: [[ 4.12869097e-07 -3.42456402e-04  6.35927354e-02]
 [ 3.42077581e-04  3.68747482e-07 -2.22546856e-01]
 [-6.40702175e-02  2.18090746e-01  1.00000000e+00]]
F: [[-5.28797489e-02  7.03027042e-01 -8.84007724e-02]
 [-4.69709262e-01  5.22651987e-01 -3.36920963e-02]
 [-1.46535781e-02  4.73553009e-05  4.86072764e-04]]
abs scale: 0.2519 | progress: 73 | len(src): 309 
12295.810492813456
En: [[ 1.02306351e-06 -6.60619617e-04  1.00421738e-01]
 [ 6.46653680e-04  5.14759519e-06 -6.99939323e-01]
 [-9.95124048e-02  7.00069172e-01  7.86886214e-06]]
E: [[ -82898.78455704  354457.84381577   14739.16361451]
 [ 245921.47535457 -258384.16663274  145832.36519315]
 [ -11

85142.76466721785
En: [[-1.79501446e-07 -4.45822283e-04  7.06216566e-02]
 [ 4.15359347e-04  3.62305568e-05 -7.03571179e-01]
 [-6.60929324e-02  7.04011028e-01  4.15917747e-05]]
E: [[-101999.16556028  344779.14286404   -3499.37621795]
 [ 261802.32707527 -265254.68935784  157618.68281776]
 [ -23448.32366062  227726.76059973   34805.98795852]]
Fn: [[-5.19627855e-08 -1.77474405e-04  3.20219141e-02]
 [ 1.76145080e-04  3.03504374e-07 -1.31904452e-01]
 [-3.20682672e-02  1.27649866e-01  1.00000000e+00]]
F: [[-1.95919906e-01  6.62251469e-01  1.02098408e-01]
 [ 5.02869675e-01 -5.09500970e-01 -1.13082798e-02]
 [ 4.05479211e-03  8.53155643e-04  3.20160479e-04]]
abs scale: 0.2728 | progress: 85 | len(src): 284 
13883.116309424022
En: [[-2.12242885e-04 -3.01922148e-02  6.00122736e-02]
 [ 3.09447508e-02 -7.58142548e-04 -7.03877456e-01]
 [ 5.64361105e-02 -7.04201544e-01  6.62107791e-04]]
E: [[-127640.03842025  299548.03964672  -35827.8308563 ]
 [ 347313.60884184  115761.07348326  321158.11107939]
 [ -2

16231.623734712572
En: [[ 2.43224026e-06 -7.31992113e-04  1.63796459e-01]
 [ 6.94292600e-04 -1.73308136e-06 -6.87873707e-01]
 [-1.57874185e-01  6.89256997e-01  1.29662319e-05]]
E: [[-130996.25646852  340811.50289652  -28864.77386696]
 [ 329935.2454175  -126583.44998808  248385.49334379]
 [ -31626.84568784  257594.06137159   35118.05026467]]
Fn: [[-7.27538216e-07 -2.43125958e-04  4.46176784e-02]
 [ 2.42947712e-04 -1.31339941e-06 -1.58705354e-01]
 [-4.29703629e-02  1.49331770e-01  1.00000000e+00]]
F: [[-2.51617492e-01  6.54630430e-01  2.15767833e-01]
 [ 6.33739324e-01 -2.43141377e-01 -2.90885761e-02]
 [-1.15634350e-03 -1.03511402e-03  2.57993889e-04]]
abs scale: 0.4577 | progress: 97 | len(src): 104 
61034.32683908497
En: [[ 4.93747254e-04  1.56033008e-02 -1.88955851e-01]
 [-1.70896958e-02  1.57219019e-03  6.81185053e-01]
 [-1.80901306e-01  6.83385882e-01 -1.68144447e-03]]
E: [[-120887.08784284  335500.5305728   -21900.11172779]
 [ 362098.77796893  -36372.81373154  297176.96966109]
 [ -1

81743.71046470606
En: [[-1.52819828e-06  5.70108021e-04 -1.03687906e-01]
 [-5.56863833e-04 -2.17829564e-05  6.99463011e-01]
 [ 1.03740524e-01 -6.99455204e-01 -2.32264052e-05]]
E: [[-105897.19782889  336626.44955189   -8928.89353626]
 [ 339559.01142471 -157731.38680608  249063.44908451]
 [  -8117.1642315   246598.13941039   52123.07426428]]
Fn: [[-2.96130366e-07 -6.53113388e-04  1.22120440e-01]
 [ 6.51981494e-04 -6.88635046e-07 -3.89743127e-01]
 [-1.21584409e-01  3.84043064e-01  1.00000000e+00]]
F: [[-2.03407243e-01  6.46591783e-01 -1.52011726e-01]
 [ 6.52224645e-01 -3.02970307e-01 -1.57197647e-02]
 [-6.75334496e-04  1.09969415e-03 -4.73591917e-04]]
abs scale: 0.6061 | progress: 109 | len(src): 127 
29312.637567291295
En: [[ 9.02285967e-07  6.27735060e-04  2.00433877e-02]
 [-6.47339544e-04  1.12468285e-04 -7.06822348e-01]
 [-1.95543173e-02  7.06836064e-01  1.12488543e-04]]
E: [[-129911.58022395  314812.03075016  -34188.60649175]
 [ 374879.29283626  -59290.95146055  302476.43671786]
 [ -

14946.393182059284
En: [[ 4.44461686e-07 -1.12590141e-03  1.70642367e-01]
 [ 1.13037092e-03 -3.45993404e-06 -6.86206898e-01]
 [-1.71411703e-01  6.86015129e-01 -5.54545353e-06]]
E: [[-120606.82889592  325233.04170905  -23797.74844156]
 [ 323735.31641021  165704.20924591  313252.42478188]
 [ -24333.58090866  314456.28955135   54940.08431353]]
Fn: [[ 2.34734011e-06 -3.46905652e-03  6.33161092e-01]
 [ 3.47003012e-03  1.08376150e-07 -2.08365596e+00]
 [-6.37655492e-01  2.08771129e+00  1.00000000e+00]]
F: [[-0.23166149  0.62470734  0.24626437]
 [ 0.62183051  0.3182845   0.08629354]
 [ 0.0009101   0.00116648  0.00077367]]
abs scale: 0.7218 | progress: 121 | len(src): 94 
4124.721285413805
En: [[ 3.84958505e-06 -9.45417366e-04  2.57324711e-01]
 [ 9.48041636e-04  6.62662389e-06 -6.58622117e-01]
 [-2.60880829e-01  6.57221653e-01  2.41847408e-07]]
E: [[-142718.3114253   295674.72722032  -49525.66256988]
 [ 346178.14400367  140956.33946736  326194.02322408]
 [ -37637.67429982  283559.51553682   363

17548.051374702074
En: [[ 6.21489642e-07 -9.91920355e-04  1.78785438e-01]
 [ 9.97528343e-04  3.95518365e-06 -6.84130668e-01]
 [-1.80307502e-01  6.83731103e-01  1.49226398e-07]]
E: [[-74613.24596746 346345.28468759  19792.73587724]
 [ 98237.88142819 353208.91554718 167623.78955666]
 [-39502.25551774 377209.4190724   56874.97340944]]
Fn: [[ 4.46985408e-07  1.37227529e-03 -2.45724291e-01]
 [-1.37140640e-03 -8.79817709e-07  8.12013491e-01]
 [ 2.44793915e-01 -8.15757715e-01  1.00000000e+00]]
F: [[-1.43317056e-01  6.65259713e-01 -2.01232010e-01]
 [ 1.88695235e-01  6.78443369e-01  2.20804638e-02]
 [-3.80196218e-03 -1.43392384e-03 -3.13236776e-04]]
abs scale: 0.7390 | progress: 133 | len(src): 78 
5888.580809518011
En: [[ 3.10390238e-06 -1.04115375e-03  2.04970279e-01]
 [ 1.04200547e-03  1.03592079e-05 -6.76746699e-01]
 [-2.07540960e-01  6.75962773e-01  5.54542616e-06]]
E: [[ -55750.2959603   357213.85586171   38613.95197815]
 [  48423.43755975 -357528.34479775  -44713.87265127]
 [ -35498.1240

12051.914472147546
En: [[ 1.44333943e-07 -1.19329347e-03  1.93228144e-01]
 [ 1.21146825e-03 -2.65643596e-05 -6.80192205e-01]
 [-1.94884533e-01  6.79719482e-01 -3.22781815e-05]]
E: [[-125244.19414392  308211.71392887  -31786.71550186]
 [ 375205.02945357  -39341.11767762  307523.30262968]
 [ -15920.39732324  250954.34813775   46818.7673942 ]]
Fn: [[ 1.79706909e-06  5.47621057e-04 -9.64551956e-02]
 [-5.46611537e-04  2.17642148e-06  3.33237804e-01]
 [ 9.41425043e-02 -3.35714038e-01  1.00000000e+00]]
F: [[-2.40568936e-01  5.92012784e-01  2.55124606e-01]
 [ 7.20693485e-01 -7.55663836e-02 -3.80108459e-02]
 [ 1.74078674e-03 -4.58666143e-05  1.28610685e-03]]
abs scale: 0.7580 | progress: 145 | len(src): 62 
1494.7579666586826
En: [[-2.59661323e-06 -1.17636620e-03  2.20284806e-01]
 [ 1.17859899e-03  2.62077704e-06 -6.71917563e-01]
 [-2.19467344e-01  6.72185022e-01  2.88869392e-06]]
E: [[-125697.2570204   322862.65313274  -28677.70693988]
 [ 343620.69554118 -136223.21225575  257652.33460351]
 [ -

28915.09411290867
En: [[-7.98100349e-06 -9.09111514e-04  1.56148166e-01]
 [ 9.11728197e-04  1.54189974e-05 -6.89649846e-01]
 [-1.51357464e-01  6.90717091e-01  2.00765532e-05]]
E: [[-118427.83825592  325970.41585641  -22077.1317192 ]
 [ 317880.34053729 -205318.30011544  219377.65844631]
 [ -23900.11520982  226195.76705103   33900.71363179]]
Fn: [[ 4.09984511e-09 -3.33105862e-04  6.09566111e-02]
 [ 3.33853201e-04  3.09323999e-07 -1.82112219e-01]
 [-6.31715831e-02  1.82777255e-01  1.00000000e+00]]
F: [[-2.27476086e-01  6.26123683e-01 -1.65155912e-01]
 [ 6.10584273e-01 -3.94375207e-01  2.38614980e-02]
 [-5.63246231e-03  1.08418688e-03  2.42615858e-04]]
abs scale: 0.7962 | progress: 157 | len(src): 68 
7169.904133611315
En: [[-3.56683848e-06 -1.09635571e-03  1.62853695e-01]
 [ 1.10038932e-03  1.37614699e-05 -6.88096981e-01]
 [-1.61755460e-01  6.88355996e-01  1.37001419e-05]]
E: [[ -81600.66450425  353698.71569383   15963.35850843]
 [ 151434.62443865 -318118.0533028    51691.52150919]
 [ -32

22700.29682947524
En: [[-3.14511907e-06 -1.14214715e-03  1.85713585e-01]
 [ 1.14641498e-03  6.35449386e-06 -6.82282306e-01]
 [-1.84870628e-01  6.82511210e-01  6.03645193e-06]]
E: [[-150922.35376674  312503.89785329  -52764.21232583]
 [ 365460.56769926  -91669.84682501  286789.24201196]
 [ -39945.71394073  242045.00863009   24131.7111514 ]]
Fn: [[-5.27304204e-06  6.71559375e-03 -9.05514004e-01]
 [-6.69561812e-03  2.23825706e-04  2.07624971e+00]
 [ 9.16999522e-01 -2.14305807e+00  1.00000000e+00]]
F: [[-2.89891522e-01  6.00257207e-01 -1.78236417e-01]
 [ 7.01976331e-01 -1.76079360e-01  9.33881917e-03]
 [ 4.73435810e-03  8.47655956e-04  9.31557506e-05]]
abs scale: 0.7762 | progress: 169 | len(src): 74 
37974.69639254594
En: [[ 1.31238474e-06 -1.04810738e-03  1.94273977e-01]
 [ 1.05639744e-03  2.20637729e-06 -6.79894482e-01]
 [-1.96587707e-01  6.79229103e-01 -3.64653228e-06]]
E: [[-132091.56825531  316818.26574162  -35535.11479558]
 [ 374183.39867043  -10726.73995504  313542.12165443]
 [ -21

10559.932799786475
En: [[ 3.17165585e-07 -1.22167005e-03  2.44219561e-01]
 [ 1.21888309e-03  9.19641243e-06 -6.63592731e-01]
 [-2.44477169e-01  6.63497874e-01  8.56613886e-06]]
E: [[-126164.09356787  335723.45596341  -26281.63820263]
 [ 362217.54243692  -56029.38305582  292579.05977913]
 [ -19810.61161882  270199.3831754    47888.11863213]]
Fn: [[ 1.93350912e-06  7.71062011e-04 -1.39771446e-01]
 [-7.70379058e-04  3.34585601e-06  4.51597300e-01]
 [ 1.37241683e-01 -4.53607894e-01  1.00000000e+00]]
F: [[-2.42335878e-01  6.44857314e-01 -1.72561668e-01]
 [ 6.95747131e-01 -1.07621189e-01 -2.58688544e-03]
 [-6.86998896e-04  1.13259129e-03  8.32286074e-05]]
abs scale: 0.6847 | progress: 181 | len(src): 81 
30485.071256680865
En: [[ 3.62040341e-06 -1.10321211e-03  1.98735319e-01]
 [ 1.11527019e-03 -2.13875095e-05 -6.78603747e-01]
 [-2.01724888e-01  6.77721060e-01 -2.75468468e-05]]
E: [[-9.59752308e+04  3.38479291e+05 -1.77797267e+02]
 [ 3.22115932e+05 -1.60344665e+05  2.33722772e+05]
 [-3.91285

34769.17614383789
En: [[ 2.20328655e-07 -1.14831532e-03  1.84479024e-01]
 [ 1.14127132e-03  3.59501877e-06 -6.82617158e-01]
 [-1.83690909e-01  6.82829652e-01  6.45839826e-06]]
E: [[-121286.61206463  305160.79088981  -29159.67536834]
 [ 317871.14087665  201180.39087124  316687.83670446]
 [ -26311.41536691  305997.8397822    51234.3653962 ]]
Fn: [[ 1.85775526e-06 -6.88010166e-04  1.14533113e-01]
 [ 6.89237795e-04  4.03375192e-06 -4.33226824e-01]
 [-1.16927157e-01  4.30414900e-01  1.00000000e+00]]
F: [[-2.32967216e-01  5.86152574e-01  2.75277217e-01]
 [ 6.10566603e-01  3.86427115e-01 -6.51767337e-02]
 [ 2.70071426e-03  1.04521345e-03 -5.39665018e-05]]
abs scale: 0.5633 | progress: 193 | len(src): 64 
2854.814575264805
En: [[-8.11535122e-06 -6.62859418e-04  2.77460631e-01]
 [ 6.54887730e-04  2.58259461e-05 -6.50396149e-01]
 [-2.71674367e-01  6.52834294e-01  2.94111657e-05]]
E: [[-130037.50085254  324046.17175301  -32386.50889982]
 [ 355848.27139382   95259.6324296   323426.3194826 ]
 [ -24

11235.087854777303
En: [[ 6.91379115e-07 -1.07908797e-03  2.17247078e-01]
 [ 1.08832654e-03  6.06309229e-06 -6.72906027e-01]
 [-2.19678933e-01  6.72116064e-01 -1.08308521e-06]]
E: [[ 139154.58223378 -269579.08204389   53245.50264028]
 [-330765.01980249  167765.511041   -239153.98647444]
 [  38316.91518033 -187552.02225677  -12312.66237021]]
Fn: [[ 8.79565156e-07  6.60697673e-04 -1.16681395e-01]
 [-6.60984821e-04  2.10302881e-06  3.88028206e-01]
 [ 1.15617883e-01 -3.92089813e-01  1.00000000e+00]]
F: [[ 2.67287997e-01 -5.17807259e-01  3.71656225e-01]
 [-6.35333154e-01  3.22243843e-01  1.21657544e-01]
 [-3.48462723e-03 -6.87395728e-04  1.58387362e-04]]
abs scale: 0.5929 | progress: 205 | len(src): 67 
771.4051337996789
En: [[-4.91686573e-06 -3.24327064e-04  1.10360441e-01]
 [ 2.75455790e-04  6.86338523e-05  6.98441479e-01]
 [-1.01145359e-01 -6.99835339e-01  5.58063054e-05]]
E: [[ 163277.11035494 -291464.82302113   67868.22637263]
 [-328042.725076   -142143.12135081 -311211.47876141]
 [  5

52279.53559647673
En: [[ 9.65956440e-06 -1.13523485e-03  2.52551809e-01]
 [ 1.14998229e-03  9.25290910e-06 -6.60466703e-01]
 [-2.60967458e-01  6.57186954e-01 -1.02785638e-05]]
E: [[-154908.40073303  304996.43261398  -57606.91795103]
 [ 275716.29508631  240506.06760954  290572.12540978]
 [ -64816.61411473  315278.50972387   20943.08711987]]
Fn: [[-1.99768450e-06  4.56899100e-04 -8.23199218e-02]
 [-4.57136638e-04 -1.68873980e-06  2.71651903e-01]
 [ 8.28368819e-02 -2.74501640e-01  1.00000000e+00]]
F: [[-2.97547917e-01  5.85836875e-01  2.69756775e-01]
 [ 5.29595613e-01  4.61963839e-01  4.00974694e-02]
 [-8.42896649e-04 -9.93075540e-04 -1.28818232e-04]]
abs scale: 0.7095 | progress: 217 | len(src): 86 
130552.58777608916
En: [[ 6.04372845e-06 -1.23512705e-03  2.53088809e-01]
 [ 1.25829516e-03 -3.54846608e-06 -6.60260923e-01]
 [-2.59755170e-01  6.57666869e-01 -2.27288634e-05]]
E: [[-121580.34158657  308930.22981048  -28521.96892298]
 [ 296410.66166078 -233924.20449521  194323.84427647]
 [ -3

56452.02172844442
En: [[-1.08081180e-06 -1.23376923e-03  2.41600412e-01]
 [ 1.24552098e-03 -5.64009055e-06 -6.64550748e-01]
 [-2.42761111e-01  6.64127634e-01 -1.10526319e-05]]
E: [[-138257.90478217  306587.94458568  -43567.64879417]
 [ 348423.17875046 -112231.75211886  267453.58200879]
 [ -33318.60783286  232119.69885731   27276.66629722]]
Fn: [[ 2.07543072e-06  3.83260649e-04 -6.90230849e-02]
 [-3.82363527e-04  3.64844831e-06  2.31254013e-01]
 [ 6.66799908e-02 -2.34379406e-01  1.00000000e+00]]
F: [[-2.65565660e-01  5.88893849e-01 -2.96306350e-01]
 [ 6.69250930e-01 -2.15574649e-01 -1.35209712e-02]
 [ 1.80936506e-02 -1.36755352e-03 -3.97294123e-04]]
abs scale: 0.7642 | progress: 229 | len(src): 101 
5108.168565137195
En: [[-3.91700386e-06 -1.17844878e-03  1.79973817e-01]
 [ 1.18715811e-03 -9.54592659e-06 -6.83818704e-01]
 [-1.78734976e-01  6.84143563e-01 -9.17831926e-06]]
E: [[-100046.46888639  332155.94473664   -4781.94306808]
 [   9248.63260391  368916.41626619   96172.84933889]
 [ -8

48650.67988211839
En: [[ 3.44388088e-07 -1.09698294e-03  2.06976378e-01]
 [ 1.09968609e-03  1.29350452e-06 -6.76135763e-01]
 [-2.07704995e-01  6.75912296e-01 -7.29671527e-07]]
E: [[ 143848.71228428 -294345.36337697   51226.9350798 ]
 [-367311.04052003  -64891.89182721 -325842.26769533]
 [  33529.21396396 -264209.989801    -34783.58963066]]
Fn: [[ 1.17423685e-06  1.10513545e-03 -1.94027874e-01]
 [-1.10533085e-03  6.66827984e-07  6.64031941e-01]
 [ 1.92178492e-01 -6.65818847e-01  1.00000000e+00]]
F: [[ 2.76304478e-01 -5.65378310e-01  3.00831696e-01]
 [-7.05530718e-01 -1.24644288e-01  1.38363148e-02]
 [-1.04845185e-03  5.92317146e-04  8.97919683e-04]]
abs scale: 0.6551 | progress: 241 | len(src): 99 
32553.04065421643
En: [[ 7.61900466e-07 -1.21361700e-03  1.80334012e-01]
 [ 1.21868277e-03 -6.13680866e-06 -6.83723748e-01]
 [-1.81212604e-01  6.83491415e-01 -8.50101507e-06]]
E: [[ 113847.88968102 -281959.99030762   28368.57036421]
 [-282121.77714067  248156.5701082  -178936.09810735]
 [  28

36665.80654067042
En: [[-2.94471313e-06 -1.07012570e-03  2.03866455e-01]
 [ 1.07203091e-03  1.09952377e-05 -6.77079989e-01]
 [-2.03066353e-01  6.77320396e-01  1.05815072e-05]]
E: [[-97666.03161574 341375.24552329   -876.10928741]
 [ 45388.23319252 359104.75959069 124441.9357252 ]
 [-71634.96284694 374424.73433927  29072.16202012]]
Fn: [[-2.23530724e-06 -1.08089304e-03  1.93834997e-01]
 [ 1.08564967e-03 -2.52439498e-06 -3.90905091e-01]
 [-1.94983333e-01  3.87986111e-01  1.00000000e+00]]
F: [[-0.18759683  0.65571327 -0.20549612]
 [ 0.08718168  0.6897681   0.09610588]
 [ 0.00071814  0.00079103  0.0008533 ]]
abs scale: 0.5764 | progress: 253 | len(src): 138 
5019.147993698163
En: [[-5.20236357e-06 -1.16733399e-03  2.01408757e-01]
 [ 1.16968727e-03  1.34328781e-05 -6.77814970e-01]
 [-1.99630855e-01  6.78340748e-01  1.43581808e-05]]
E: [[-105962.95944611  332675.05156851  -10013.57355757]
 [ 276080.4718544  -231691.17225018  177726.03085055]
 [ -23380.20830155  225541.8447972    34116.581155

3819.19871496869
En: [[-3.07858023e-06 -1.12137267e-03  1.91572020e-01]
 [ 1.13164336e-03 -1.28945381e-06 -6.80660621e-01]
 [-1.91408927e-01  6.80706519e-01 -3.82821216e-06]]
E: [[-136791.51191268  304260.25966619  -42921.42449083]
 [ 141306.28380786  327785.38385283  197886.18608935]
 [ -81708.77439371  335566.42924791   11147.48461009]]
Fn: [[ 3.49620592e-06  1.51294224e-03 -2.68228860e-01]
 [-1.51478199e-03  4.69579692e-06  8.65596760e-01]
 [ 2.67075514e-01 -8.73804859e-01  1.00000000e+00]]
F: [[-2.62749014e-01  5.84422834e-01 -3.44765354e-01]
 [ 2.71420983e-01  6.29609872e-01 -2.15717482e-02]
 [ 2.34475837e-03  2.76434322e-04 -9.49419979e-04]]
abs scale: 0.6571 | progress: 265 | len(src): 96 
3143.896623323206
En: [[-1.76515258e-06 -1.12557447e-03  2.21179310e-01]
 [ 1.13257679e-03  7.70948072e-06 -6.71623723e-01]
 [-2.21921827e-01  6.71378761e-01  3.44739570e-06]]
E: [[ 157531.61285808 -288107.14397476   64252.02781696]
 [-276479.69721656 -260502.01535877 -295948.85365452]
 [  668

21108.057083988973
En: [[-7.36508698e-08 -1.07526269e-03  2.21111022e-01]
 [ 1.07959816e-03  3.42317849e-06 -6.71646298e-01]
 [-2.22083267e-01  6.71325456e-01  2.29509981e-07]]
E: [[-148226.65572311  309513.1611967   -51236.91854717]
 [ 164678.07466757  335308.11272481  219441.40019218]
 [ -85773.13142963  341805.42862809    9283.68685996]]
Fn: [[ 5.29804059e-06 -1.69143540e-03  3.43821819e-01]
 [ 1.68517533e-03  2.64744621e-06 -9.99733395e-01]
 [-3.50168727e-01  1.00729281e+00  1.00000000e+00]]
F: [[-0.28471363  0.5945126  -0.22477158]
 [ 0.3163135   0.64405952 -0.00990606]
 [-0.00168144 -0.0009058  -0.00140661]]
abs scale: 0.8380 | progress: 277 | len(src): 65 
3709.8917539917966
En: [[-2.12841750e-06 -1.03830786e-03  2.57922869e-01]
 [ 1.03948953e-03  6.74769375e-06 -6.58387961e-01]
 [-2.57575585e-01  6.58523914e-01  5.71518528e-06]]
E: [[-151292.14055708  304556.46166527  -55004.28269295]
 [ 319029.44907092 -203724.88020153  220720.27532957]
 [ -51385.18719514  208485.36038479    6

9073.156907779223
En: [[ 2.85430172e-06 -1.01377061e-03  2.13066782e-01]
 [ 1.02654801e-03 -6.11222714e-06 -6.74241426e-01]
 [-2.16847923e-01  6.73034875e-01 -1.47101783e-05]]
E: [[-125486.71249748  322731.07255261  -28523.10944302]
 [ 268643.74381257 -250327.2855906   166982.75759448]
 [ -41654.7090558   212675.53265509   15906.34300785]]
Fn: [[-2.23249688e-06  8.46944290e-04 -1.47999982e-01]
 [-8.47091926e-04 -7.86766387e-07  5.07228510e-01]
 [ 1.48680686e-01 -5.10446591e-01  1.00000000e+00]]
F: [[-2.41034765e-01  6.19901555e-01  2.41515574e-01]
 [ 5.16010663e-01 -4.80828426e-01  2.59404082e-04]
 [ 7.62555920e-06 -4.59784969e-04 -4.27076969e-02]]
abs scale: 0.9012 | progress: 289 | len(src): 66 
8690.117565219145
En: [[-5.25990396e-07 -1.05803242e-03  2.02298616e-01]
 [ 1.05900087e-03  1.29638866e-05 -6.77550102e-01]
 [-2.02840679e-01  6.77388033e-01  1.07440521e-05]]
E: [[-127151.69551953  324427.51310831  -29827.94134631]
 [ 341147.13647368 -156141.89068111  250793.44156038]
 [ -25

12897.10610313356
En: [[ 3.89636878e-06 -1.14236547e-03  1.96132083e-01]
 [ 1.14328260e-03  4.53013946e-06 -6.79360654e-01]
 [-1.98622462e-01  6.78636731e-01  4.33566502e-08]]
E: [[-127596.46356475  326808.16199149  -29352.94954388]
 [ 114626.35441843  350837.64788508  180880.11377031]
 [ -80334.49137163  360136.53226671   18534.07707178]]
Fn: [[-3.79020071e-05  1.18208030e-02 -2.06394086e+00]
 [-1.18284778e-02 -2.25294305e-05  7.11329062e+00]
 [ 2.08766215e+00 -7.11356898e+00  1.00000000e+00]]
F: [[-2.45087173e-01  6.27732825e-01  2.07932799e-01]
 [ 2.20174199e-01  6.73888640e-01 -6.58811584e-03]
 [-7.24119355e-04 -1.07577744e-03  2.59343621e-04]]
abs scale: 0.9607 | progress: 301 | len(src): 69 
52973.81261531486
En: [[ 3.85997464e-06 -1.15319449e-03  2.00094526e-01]
 [ 1.15298901e-03  2.02522264e-06 -6.78204138e-01]
 [-2.02243491e-01  6.77566410e-01 -1.42566049e-06]]
E: [[-90649.64406654 348223.11542854   6963.42935664]
 [-43517.37317887 358359.27677062  49005.96795181]
 [-87007.707

41519.14654297191
En: [[-0.00074336 -0.07296664  0.07306575]
 [ 0.07745814 -0.00865323 -0.69907988]
 [ 0.0687052  -0.69982438  0.00865023]]
E: [[ -79881.57908875  353154.64999605   16987.67678123]
 [ 139483.48735552 -333974.07058291   37820.04442978]
 [ -34067.42029804  218339.07663636   23413.14741069]]
Fn: [[-4.14932981e-07 -4.23931320e-04  7.27340721e-02]
 [ 4.23537491e-04  1.23894352e-06 -2.63557806e-01]
 [-7.37670483e-02  2.62436792e-01  1.00000000e+00]]
F: [[-1.53436466e-01  6.78339135e-01 -1.81295017e-01]
 [ 2.67919758e-01 -6.41497096e-01 -1.17457743e-02]
 [ 2.59811533e-03 -1.38432899e-04  1.06374025e-03]]
abs scale: 0.9175 | progress: 313 | len(src): 75 
28537.89349844103
En: [[-1.01121890e-05 -1.12396936e-03  1.68817245e-01]
 [ 1.11853702e-03 -5.68667276e-06 -6.86658200e-01]
 [-1.62008148e-01  6.88296520e-01  6.41222667e-06]]
E: [[-126868.61900954  324616.59776985  -29487.31930769]
 [ 349704.83964292 -156191.69878256  258018.74388158]
 [ -23399.47092018  236819.97766894   3690

220391.75142694562
En: [[-6.32212913e-07  1.12388550e-03 -1.54289156e-01]
 [-1.11936171e-03  6.01955164e-06  6.90067827e-01]
 [ 1.53891809e-01 -6.90156537e-01  4.09576909e-06]]
E: [[-127239.87796475  317322.80715275  -31344.74690237]
 [ 337478.10728725 -177257.1508742   242655.37447038]
 [ -26644.15661382  225611.78075238   31652.31979756]]
Fn: [[ 9.57292931e-06  4.51013950e-03 -7.98379694e-01]
 [-4.50762615e-03  1.52620847e-05  2.72590609e+00]
 [ 7.86434432e-01 -2.71461415e+00  1.00000000e+00]]
F: [[-2.44402244e-01  6.09513364e-01  1.79244842e-01]
 [ 6.48227646e-01 -3.40475377e-01  2.24531847e-02]
 [ 2.01051132e-03 -1.06158489e-04  1.22684935e-03]]
abs scale: 0.9008 | progress: 325 | len(src): 76 
76047.14084470028
En: [[-1.19776096e-06 -1.14674388e-03  2.16798225e-01]
 [ 1.14108819e-03 -1.11463079e-05 -6.73050691e-01]
 [-2.14581025e-01  6.73760835e-01 -4.81133631e-06]]
E: [[-117083.13743682  339445.15362511  -17456.86919247]
 [ 304780.84595178 -197579.41944352  210175.75276339]
 [ -2

597068.0479509601
En: [[-5.15720474e-06 -8.01626465e-04  1.63674082e-02]
 [ 7.96563993e-04  1.65458403e-05 -7.06916878e-01]
 [-1.17233026e-02  7.07009138e-01  2.18869939e-05]]
E: [[-128246.12880271  326727.68333894  -29936.09975413]
 [ 354334.68293109 -113142.32011287  272239.89931928]
 [ -23456.78148657  248915.81150988   39928.88312478]]
Fn: [[ 1.68515617e-07 -1.53125860e-04  2.63195668e-02]
 [ 1.53270454e-04  2.34461138e-07 -9.36930117e-02]
 [-2.77728111e-02  9.25503599e-02  1.00000000e+00]]
F: [[-2.46335049e-01  6.27578242e-01  1.87103046e-01]
 [ 6.80605742e-01 -2.17323667e-01  8.68413747e-04]
 [ 9.62424260e-04 -1.25469564e-03  1.94559216e-04]]
abs scale: 0.9176 | progress: 337 | len(src): 94 
172278.54087201238
En: [[-1.82350805e-06 -1.07155285e-03  1.54946743e-01]
 [ 1.05896158e-03  2.12166935e-06 -6.89920563e-01]
 [-1.52156366e-01  6.90541305e-01  8.91113206e-06]]
E: [[-140997.51214565  320132.15234477  -42535.12213045]
 [ 367077.99982789  -85228.77720018  289710.97481082]
 [ -3

26658.751968860357
En: [[-4.32196883e-04  3.08574367e-02  2.26071108e-01]
 [-2.94376538e-02  2.39638881e-03 -6.69375742e-01]
 [ 2.19866857e-01 -6.71312034e-01 -1.41465566e-03]]
E: [[ 139440.61298002 -316042.48727438   41922.80265854]
 [-370771.67172206   -5176.30926543 -314470.51184324]
 [  28976.28585473 -268233.96780261  -39919.38374087]]
Fn: [[-3.36442282e-07 -3.44313626e-04  6.12203975e-02]
 [ 3.44268225e-04  1.65019935e-07 -2.10793918e-01]
 [-6.24047625e-02  2.09952657e-01  1.00000000e+00]]
F: [[ 2.67837405e-01 -6.07054127e-01 -2.29020213e-01]
 [-7.12177895e-01 -9.94265020e-03 -5.05932147e-04]
 [-9.09009846e-04  8.89108757e-04  2.66439829e-04]]
abs scale: 0.8498 | progress: 349 | len(src): 68 
20648.58697009337
En: [[-2.25921358e-06 -1.12636377e-03  1.88533934e-01]
 [ 1.12569792e-03 -8.84894493e-06 -6.81508395e-01]
 [-1.86781951e-01  6.81990638e-01 -5.32073945e-06]]
E: [[ -93614.95951392  347309.89095584    4271.09155646]
 [ 244568.32311559 -263332.84958353  143532.65031599]
 [ -2

156995.38287507187
En: [[ 3.71123975e-05  1.59787553e-04 -6.51958395e-01]
 [-2.31570258e-04 -6.85310304e-05 -2.73770403e-01]
 [ 6.19901919e-01  3.40178693e-01  9.50943738e-06]]
E: [[ 124762.45739995 -324091.78338737   27894.51440836]
 [-368686.41225303   69553.07439686 -294825.10784771]
 [  17076.35285327 -257132.8965236   -47063.94990479]]
Fn: [[ 1.21799492e-06  1.56794500e-04 -2.74343003e-02]
 [-1.56765363e-04  1.38739361e-06  9.26119861e-02]
 [ 2.49873990e-02 -9.27366016e-02  1.00000000e+00]]
F: [[ 2.39643616e-01 -6.22515207e-01  1.87064119e-01]
 [-7.08172531e-01  1.33597483e-01 -2.63648271e-02]
 [ 7.15818932e-05 -8.55248123e-04 -6.48519204e-04]]
abs scale: 0.7684 | progress: 361 | len(src): 51 
10959.945621754527
En: [[-2.91613808e-06 -1.14749195e-03  2.18364912e-01]
 [ 1.14441102e-03 -2.44905252e-06 -6.72544017e-01]
 [-2.16149492e-01  6.73259297e-01  2.18054640e-06]]
E: [[ -91027.56078572  346465.65219301    5918.55786704]
 [ 205874.42689757 -288338.80333677  104836.07591245]
 [ -

5975.875340831641
En: [[-0.00250312  0.40055439  0.41443767]
 [-0.38591359 -0.00956801  0.41994468]
 [ 0.40366327  0.42339697 -0.01441952]]
E: [[-129595.13138965  319457.38321669  -33109.3779654 ]
 [ 271729.47429432 -255943.10237984  168237.37442953]
 [ -44383.25341032  208564.92259769   12335.0989719 ]]
Fn: [[ 2.38261441e-07 -3.59107768e-04  6.13010287e-02]
 [ 3.59150446e-04  1.09520083e-06 -2.27063050e-01]
 [-6.25958181e-02  2.25229034e-01  1.00000000e+00]]
F: [[-2.48926212e-01  6.13613456e-01 -2.17498557e-01]
 [ 5.21937731e-01 -4.91615282e-01 -9.27922975e-03]
 [ 4.22660205e-03  4.73999060e-05  3.07553313e-04]]
abs scale: 0.6582 | progress: 373 | len(src): 77 
21225.392350745096
En: [[-0.00232943  0.2671869   0.36159228]
 [-0.25777017 -0.00160847  0.54875858]
 [ 0.35040884  0.55444346 -0.0088778 ]]
E: [[-139279.05164178  318895.14190289  -41423.92426427]
 [ 332360.65375893 -162847.70791082  241743.75338985]
 [ -38034.40835854  230391.84244873   22924.38769127]]
Fn: [[ 4.25351892e-07 

65194.343734185466
En: [[ 1.76637513e-07 -6.87047895e-04  1.04658023e-01]
 [ 6.65360675e-04  3.25559270e-05 -6.99318416e-01]
 [-1.02310202e-01  6.99665746e-01  3.72717453e-05]]
E: [[-197911.95153662  253008.89402836 -106397.02043219]
 [ 385382.10007956   28245.89598425  332335.00114846]
 [ -74866.01650015  220510.84201056  -10262.82402222]]
Fn: [[ 6.89332121e-07 -3.05639820e-04  5.77189945e-02]
 [ 3.05617341e-04  4.79461308e-06 -2.02304804e-01]
 [-5.90781506e-02  1.99286053e-01  1.00000000e+00]]
F: [[-3.80149099e-01  4.85979257e-01  2.61247622e-01]
 [ 7.40241593e-01  5.42546917e-02 -6.58239285e-03]
 [ 1.07175970e-02  1.04746400e-03  1.57483103e-04]]
abs scale: 0.7341 | progress: 385 | len(src): 80 
4069.587511933656
En: [[-2.69970801e-05 -7.08273643e-02  1.16457326e-01]
 [ 7.04993440e-02  2.70006994e-03 -6.93827097e-01]
 [ 1.16676588e-01 -6.93849446e-01 -2.68454196e-03]]
E: [[-151810.23008172  299019.79528197  -56422.92975363]
 [ 269207.71912341 -258133.50901849  165600.67746039]
 [ -6

61288.20698345836
En: [[-1.56034434e-06  6.03369630e-04  6.62788658e-02]
 [-6.22330694e-04  8.65055514e-05 -7.03993414e-01]
 [-6.92196407e-02  7.03710352e-01  9.00656965e-05]]
E: [[-165974.64057502  242237.83438873  -82489.13593821]
 [ 314223.5941755  -185140.17566038  221188.95186791]
 [ -64941.79952215  160290.92264999  -16700.2031485 ]]
Fn: [[ 3.19417475e-06 -5.36468031e-04  9.50333610e-02]
 [ 5.37440464e-04  3.33640080e-06 -3.40171209e-01]
 [-9.79759802e-02  3.36654255e-01  1.00000000e+00]]
F: [[-3.18803941e-01  4.65290215e-01 -4.21450827e-01]
 [ 6.03560398e-01 -3.55617084e-01  1.16157273e-01]
 [-2.64317712e-03 -3.09594707e-04 -2.22185247e-04]]
abs scale: 0.8737 | progress: 397 | len(src): 102 
96577.84749091916
En: [[ 7.27015923e-06 -1.15743591e-03  2.14409254e-01]
 [ 1.15473518e-03 -5.87209106e-06 -6.73815514e-01]
 [-2.17472252e-01  6.72833168e-01 -9.12017991e-06]]
E: [[-145801.29746403  281543.22187504  -55471.92538291]
 [ 270946.09222547 -248000.04995349  169545.52501071]
 [ -5

77377.54453974374
En: [[ 1.93562394e-07 -1.17234045e-03  1.92606092e-01]
 [ 1.16846960e-03 -7.80236659e-06 -6.80368674e-01]
 [-1.91786479e-01  6.80600153e-01 -4.78943515e-06]]
E: [[ -92877.90001962  339388.30025856    2706.67410637]
 [ 191050.4222969  -318242.20028249   85168.88812236]
 [ -32694.89572799  210478.69994287   22690.29833924]]
Fn: [[ 1.90087603e-06 -1.13284151e-03  1.86960074e-01]
 [ 1.13614763e-03  1.45436897e-06 -6.99479754e-01]
 [-1.88837736e-01  6.93804890e-01  1.00000000e+00]]
F: [[-1.78399787e-01  6.51896743e-01 -1.86452204e-01]
 [ 3.66969480e-01 -6.11279333e-01  1.04477161e-02]
 [ 3.03794369e-04  8.82817709e-04  8.23840200e-04]]
abs scale: 0.9475 | progress: 409 | len(src): 109 
145309.0390380763
En: [[-8.29469617e-08 -1.11701725e-03  2.04370902e-01]
 [ 1.11298934e-03 -4.68498578e-06 -6.76927838e-01]
 [-2.03412870e-01  6.77216328e-01 -1.61256843e-06]]
E: [[-134457.63822699  295139.30498894  -43130.04591261]
 [ 291436.36689124 -213090.45884547  195065.36257726]
 [ -4

23939.746460515744
En: [[-3.00907501e-06 -9.85107585e-04  2.98780428e-01]
 [ 9.77641661e-04  6.39256387e-06 -6.40881651e-01]
 [-2.96038322e-01  6.42152903e-01  1.17730583e-05]]
E: [[-154750.46146748  275465.87784614  -64475.00143396]
 [ 318967.34997921  158692.45295094  307366.9356429 ]
 [ -54333.32173669  270731.6677875    19154.66290374]]
Fn: [[ 5.57806072e-06  1.85029620e-03 -3.38720504e-01]
 [-1.85057562e-03  6.61440943e-06  1.11292401e+00]
 [ 3.33238447e-01 -1.11241732e+00  1.00000000e+00]]
F: [[-2.97244548e-01  5.29114612e-01  3.70829236e-01]
 [ 6.12672200e-01  3.04816322e-01 -1.60018006e-01]
 [-1.67865275e-02 -5.91689868e-04  9.84779356e-04]]
abs scale: 0.9586 | progress: 421 | len(src): 100 
35292.68220654517
En: [[-7.57786679e-08  3.38387305e-03 -6.08510867e-01]
 [-3.40909511e-03  2.83329268e-04 -3.60141872e-01]
 [ 6.31343546e-01  3.18425031e-01 -1.74004007e-04]]
E: [[ 155723.74017473 -291697.82235071   61456.3720407 ]
 [-368585.00267223  -24646.95462027 -317299.50273084]
 [  

1172.6421761219826
En: [[-1.63810380e-06 -1.22163772e-03  2.32935950e-01]
 [ 1.22345175e-03 -2.13041054e-05 -6.67637148e-01]
 [-2.31190935e-01  6.68243401e-01 -1.65543882e-05]]
E: [[-130638.37481954  316928.0863834   -34263.25393678]
 [ 360045.67196765  -85450.86543984  283725.05711535]
 [ -24110.02379763  247271.80587867   39024.5757182 ]]
Fn: [[ 9.08346533e-06  6.69926410e-03 -1.21471396e+00]
 [-6.70179190e-03 -1.14010585e-05  4.11556297e+00]
 [ 1.20162561e+00 -4.09194454e+00  1.00000000e+00]]
F: [[-2.50930073e-01  6.08755185e-01  2.44555036e-01]
 [ 6.91575404e-01 -1.64133946e-01  3.77653411e-02]
 [ 4.04535562e-04 -1.63324127e-05  1.08678125e-03]]
abs scale: 0.9460 | progress: 433 | len(src): 51 
32923.76658584084
En: [[ 2.58642751e-07 -1.09129194e-03  1.80962857e-01]
 [ 1.09092632e-03 -7.87614728e-06 -6.83557795e-01]
 [-1.80734873e-01  6.83618103e-01 -6.88975002e-06]]
E: [[-114790.09784555  335241.81935493  -16543.74495599]
 [ 341905.84331884 -144110.44255642  254295.7774801 ]
 [ -1

7727.95104266463
En: [[ 2.58523082e-06  4.66180235e-03 -7.07086211e-01]
 [-4.67647044e-03  3.62099473e-04  2.71481420e-03]
 [ 7.04768420e-01 -5.72654699e-02 -3.56974800e-04]]
E: [[-106533.27170891  340725.54715763   -8264.26216476]
 [ 284925.98066593 -235841.98925466  184178.44385614]
 [ -21740.10564521  231348.11114325   37142.46661764]]
Fn: [[ 1.38662553e-06 -7.76089084e-04  1.23812625e-01]
 [ 7.81049186e-04 -1.67847936e-05 -3.74620414e-01]
 [-1.25919797e-01  3.73010883e-01  1.00000000e+00]]
F: [[-2.04629013e-01  6.54465326e-01  1.52888092e-01]
 [ 5.47285569e-01 -4.53005082e-01 -4.10270134e-02]
 [ 2.77602063e-03  3.63428153e-04  1.08800487e-03]]
abs scale: 0.9195 | progress: 445 | len(src): 64 
13593.828787085178
En: [[-1.90547420e-06 -1.12988886e-03  1.89138704e-01]
 [ 1.12233165e-03  1.90811106e-06 -6.81340801e-01]
 [-1.86975823e-01  6.81937510e-01  7.14907419e-06]]
E: [[ -96821.06288326  344152.57848532     763.82489485]
 [ 319582.48463426 -185730.67119221  225495.39104497]
 [  -5

4227.600104535726
En: [[-1.05035101e-06 -1.04506678e-03  1.88580360e-01]
 [ 1.04297706e-03 -8.36869428e-06 -6.81495681e-01]
 [-1.87207604e-01  6.81874048e-01 -5.21421940e-06]]
E: [[-103537.70266265  338256.79283085   -6292.30356313]
 [ 136001.54847424  341607.36085996  196742.44290086]
 [ -54887.54084319  367598.19108696   41817.18565258]]
Fn: [[ 3.71586079e-06  8.88534741e-04 -1.57106694e-01]
 [-8.88567881e-04  3.24632952e-06  5.48574621e-01]
 [ 1.52327505e-01 -5.46052769e-01  1.00000000e+00]]
F: [[-1.98875127e-01  6.49723345e-01  1.98218112e-01]
 [ 2.61231653e-01  6.56159113e-01  1.51403188e-02]
 [ 1.01402832e-03  3.47105183e-04  8.38811219e-04]]
abs scale: 0.8867 | progress: 457 | len(src): 78 
11696.255176903695
En: [[ 7.52493113e-07 -9.81463190e-04  1.98182451e-01]
 [ 9.77389748e-04 -1.54710183e-06 -6.78765616e-01]
 [-1.97820098e-01  6.78871302e-01  2.51023241e-07]]
E: [[-109230.38075883  337990.64598226  -11161.03100998]
 [ 246249.71819051 -268107.93094932  143849.51607685]
 [ -3

28086.87033498119
En: [[-1.38517748e-06 -1.26139055e-03  1.79415789e-01]
 [ 1.25276225e-03  2.45153440e-06 -6.83965205e-01]
 [-1.77647710e-01  6.84426551e-01  7.56338164e-06]]
E: [[-128020.56561245  289444.1665282   -38571.87733531]
 [ 335966.20820518 -166602.16710292  243897.59520336]
 [ -27668.91153596  204612.02387609   25841.76470443]]
Fn: [[ 9.00184372e-07 -5.89595302e-04  1.08578800e-01]
 [ 5.88324517e-04  1.45984026e-06 -3.58160693e-01]
 [-1.10235179e-01  3.56904874e-01  1.00000000e+00]]
F: [[-2.45901788e-01  5.55964096e-01  3.33221654e-01]
 [ 6.45323592e-01 -3.20009293e-01 -2.33681081e-02]
 [-2.18852764e-03 -4.67610292e-04 -3.51663395e-05]]
abs scale: 0.8670 | progress: 469 | len(src): 87 
16370.522879039854
En: [[-5.83681763e-06 -9.20271984e-04  2.99993594e-01]
 [ 9.06720170e-04  1.82728742e-05 -6.40314766e-01]
 [-2.95261228e-01  6.42510685e-01  2.59152479e-05]]
E: [[-132797.31544459  326656.89440697  -34069.94637797]
 [ 350006.15436551 -118034.97868072  267441.09046963]
 [ -2

3716.908077328524
En: [[ 3.20700990e-06 -1.14027203e-03  1.93209945e-01]
 [ 1.14458066e-03  6.56684876e-07 -6.80197478e-01]
 [-1.95681520e-01  6.79490574e-01 -4.44291053e-06]]
E: [[-111404.24934145  339511.04781465  -12926.51884526]
 [ 275006.61206969 -234871.52081017  176007.32233356]
 [ -28234.32970913  230554.12015399   31243.72053561]]
Fn: [[-2.26919011e-06  1.60630674e-03 -2.77022659e-01]
 [-1.60744468e-03  5.10590248e-08  9.73879539e-01]
 [ 2.77507857e-01 -9.75858936e-01  1.00000000e+00]]
F: [[-2.13985182e-01  6.52132517e-01 -2.02292972e-01]
 [ 5.28232454e-01 -4.51141007e-01 -7.38308130e-02]
 [-1.21009664e-03 -2.78916570e-04 -9.00577779e-04]]
abs scale: 0.8094 | progress: 481 | len(src): 98 
62632.550982701345
En: [[ 5.66564846e-06 -1.21095351e-03  1.71517441e-01]
 [ 1.22055942e-03 -9.68110714e-06 -6.85988548e-01]
 [-1.75479323e-01  6.84985788e-01 -1.80686920e-05]]
E: [[ 136380.10240956 -320878.49496179   38492.98486918]
 [-357157.15669108  100777.29129704 -277605.66156996]
 [  2

13080.149040680015
En: [[ 6.18315093e-06 -1.88540866e-04  1.34808952e-01]
 [ 1.27516275e-04  1.47998953e-04 -6.94137233e-01]
 [-1.34447751e-01  6.94207284e-01  1.54346553e-04]]
E: [[-113511.96725548  326097.26609163  -17933.11232377]
 [ 235209.90015126 -281711.57997227  131131.57623118]
 [ -39560.3683334   208000.42401078   16253.62695256]]
Fn: [[-1.47620662e-06 -4.34447835e-03  7.56916069e-01]
 [ 4.33676061e-03  1.84047885e-05 -2.67528196e+00]
 [-7.60157601e-01  2.68578588e+00  1.00000000e+00]]
F: [[-0.21803369  0.62636734 -0.21965903]
 [ 0.45179097 -0.54111135 -0.12107322]
 [-0.01727559 -0.00096091  0.00071884]]
abs scale: 0.6672 | progress: 493 | len(src): 75 
10956.513496558953
En: [[-6.00488619e-06 -1.25680828e-03  1.95179612e-01]
 [ 1.27490213e-03 -2.75096987e-05 -6.79634689e-01]
 [-1.93650304e-01  6.80072027e-01 -2.78196795e-05]]
E: [[-128244.75760284  326121.0595307   -30350.23539916]
 [ 217351.08461556  302512.89560289  256090.15098305]
 [ -56271.86094324  347981.00399437   35

3139.32522130946
En: [[ 1.40112626e-06 -9.63005664e-04  1.78229798e-01]
 [ 9.52819771e-04  3.16059859e-05 -6.84275686e-01]
 [-1.78828490e-01  6.84119477e-01  3.13308209e-05]]
E: [[-134022.70234008  316460.07863439  -37543.67854584]
 [ 263978.90124429 -270007.42543908  158280.4252395 ]
 [ -49986.22804471  202663.42570542    6198.76118607]]
Fn: [[ 1.49715881e-06  2.47604494e-03 -4.58427948e-01]
 [-2.46471478e-03 -4.12927151e-05  1.67755455e+00]
 [ 4.56720343e-01 -1.68047354e+00  1.00000000e+00]]
F: [[-2.57430687e-01  6.07856236e-01 -1.83984275e-01]
 [ 5.07050437e-01 -5.18630021e-01 -6.46094548e-02]
 [-3.78856150e-03 -3.54116008e-05  6.07073101e-03]]
abs scale: 0.5330 | progress: 505 | len(src): 108 
30800.781542522636
En: [[-6.90554527e-07 -1.08072611e-03  1.85447347e-01]
 [ 1.07978671e-03  8.92293866e-06 -6.82354827e-01]
 [-1.85278342e-01  6.82400742e-01  8.76752626e-06]]
E: [[ -97206.91070723  324186.50900759   -4623.57378332]
 [ 163231.08512755 -339477.84407375   56595.78091774]
 [ -4

43209.9634435913
En: [[-0.00102942  0.26068398  0.62352699]
 [-0.26174353  0.0082374  -0.21131826]
 [ 0.61616479 -0.2243252   0.00656682]]
E: [[-137606.6903553   319729.81385538  -39518.64159359]
 [ 337210.23328668 -162519.12093519  245937.50822186]
 [ -35468.18373732  231174.95938709   25531.39820858]]
Fn: [[ 1.02936633e-06 -3.60582076e-04  6.47066010e-02]
 [ 3.59808385e-04  1.51408702e-06 -2.24620581e-01]
 [-6.67243677e-02  2.24044619e-01  1.00000000e+00]]
F: [[-2.64314808e-01  6.14136740e-01  1.89526864e-01]
 [ 6.47713114e-01 -3.12166582e-01 -8.39312147e-03]
 [-6.36808764e-04 -1.44616760e-03  3.46484152e-04]]
abs scale: 0.5153 | progress: 517 | len(src): 117 
767179.0307269071
En: [[-3.44751840e-04  1.45616098e-01  3.84599967e-01]
 [-1.48919732e-01  4.57167067e-03  5.74046646e-01]
 [ 3.95764685e-01  5.67908273e-01  1.29143086e-03]]
E: [[ 142673.78411977 -304939.82870197   47091.66034484]
 [-257194.49006152  113085.06934995 -190156.02756875]
 [  58917.06119809 -230519.8338525    -577

7126.7637332823515
En: [[ 3.34994735e-07  1.05837180e-03 -1.70240085e-01]
 [-1.06028320e-03  1.21950905e-05  6.86306925e-01]
 [ 1.69867674e-01 -6.86399189e-01  1.13805702e-05]]
E: [[-118057.60406158  329016.33037144  -20756.98038845]
 [ 256931.33071016 -264113.18491116  153785.9550368 ]
 [ -38184.60130362  214683.84281087   19305.89324288]]
Fn: [[ 5.01640267e-06  1.04881086e-03 -1.80285346e-01]
 [-1.05358202e-03  9.27622909e-06  6.05132128e-01]
 [ 1.75542673e-01 -6.03553896e-01  1.00000000e+00]]
F: [[-2.26764940e-01  6.31974273e-01  2.19696839e-01]
 [ 4.93513470e-01 -5.07308369e-01  9.65505864e-04]
 [-2.44224133e-04  1.04223282e-03  2.73529203e-04]]
abs scale: 0.6569 | progress: 530 | len(src): 108 
5862.419010197824
En: [[-9.76482762e-07  2.84904549e-04 -1.92677535e-01]
 [-2.50988998e-04 -9.67192827e-05  6.80349381e-01]
 [ 1.90543893e-01 -6.80950034e-01 -9.93751844e-05]]
E: [[-135527.94269993  317836.79806877  -38477.13205729]
 [ 312472.12790807 -213595.79266112  212783.22351369]
 [ -

9697.257801923091
En: [[ 3.43731246e-06 -1.06894195e-03  1.56605764e-01]
 [ 1.06627878e-03  1.76352763e-06 -6.89545864e-01]
 [-1.58398167e-01  6.89136327e-01 -3.51108909e-07]]
E: [[-145427.17312369  310056.49488949  -48444.84009584]
 [ 318434.0920826  -206913.90134815  219432.49701019]
 [ -46573.17849737  212367.56789774   11640.76510888]]
Fn: [[ 1.11963548e-05 -3.68510639e-03  6.50911780e-01]
 [ 3.68286825e-03  1.63707442e-05 -2.29651752e+00]
 [-6.57790264e-01  2.28905832e+00  1.00000000e+00]]
F: [[-2.79336384e-01  5.95556238e-01  1.86705482e-01]
 [ 6.11647919e-01 -3.97440036e-01 -1.87231129e-02]
 [-8.15950218e-04 -1.37910710e-03 -3.65134250e-04]]
abs scale: 0.7713 | progress: 542 | len(src): 105 
1687.5055310071111
En: [[-1.09567794e-06 -1.39654685e-03  2.22697705e-01]
 [ 1.39108034e-03 -1.46004747e-06 -6.71121298e-01]
 [-2.21367712e-01  6.71561156e-01  2.96684689e-06]]
E: [[-134616.19096299  323035.85622824  -36446.75476974]
 [ 295979.0119966  -233860.664832    194020.1016657 ]
 [ -

32654.617268583246
En: [[-5.59587419e-04 -1.29705748e-01  1.11065680e-01]
 [ 1.34729200e-01 -6.94673104e-03 -6.85389000e-01]
 [ 1.10066117e-01 -6.86082552e-01  7.64240540e-03]]
E: [[-142720.81967422  310955.35751376  -46238.26450035]
 [ 332265.33961286 -172666.34836635  239361.92007985]
 [ -40971.94753918  221333.2473413    18280.90361902]]
Fn: [[ 9.41096940e-07 -3.42048794e-03  6.52087732e-01]
 [ 3.42171571e-03  2.32001818e-05 -2.25398078e+00]
 [-6.55912453e-01  2.25455158e+00  1.00000000e+00]]
F: [[-2.74138023e-01  5.97282772e-01 -2.22285343e-01]
 [ 6.38214967e-01 -3.31657367e-01  3.70530480e-02]
 [ 1.16233443e-03  1.19309159e-03 -8.50798652e-05]]
abs scale: 0.8628 | progress: 554 | len(src): 101 
2729.024448827957
En: [[-5.48095311e-04  3.93028523e-02  1.46216186e-01]
 [-3.78702517e-02  3.50750612e-03 -6.90821521e-01]
 [ 1.47469827e-01 -6.90389660e-01 -3.12189981e-03]]
E: [[-138364.16526409  318729.2341265   -40656.19115693]
 [ 296608.00669989 -233163.82095269  194743.46403883]
 [ -

38669.7416758254
En: [[-0.00074261  0.07284803  0.1020423 ]
 [-0.07141864  0.00504721 -0.69611631]
 [ 0.10541443 -0.69529673 -0.00512107]]
E: [[-124090.98617395  329537.09175686  -25748.49754885]
 [ 255907.98056332 -267077.94465268  152226.12430082]
 [ -43525.02830334  214412.28498757   14716.54381042]]
Fn: [[-1.19734848e-06  9.23721419e-04 -1.61220670e-01]
 [-9.22521799e-04 -3.18885962e-06  5.76899101e-01]
 [ 1.60511885e-01 -5.77601888e-01  1.00000000e+00]]
F: [[-2.38353855e-01  6.32974551e-01  1.93037448e-01]
 [ 4.91547820e-01 -5.13003077e-01  2.16842014e-02]
 [ 2.20465823e-03 -6.93348310e-04 -4.89212672e-04]]
abs scale: 0.9233 | progress: 566 | len(src): 71 
19462.337925344276
En: [[ 6.62869902e-07 -1.04732345e-03  1.95177896e-01]
 [ 1.04377215e-03  1.17468997e-05 -6.79635559e-01]
 [-1.95545779e-01  6.79529807e-01  1.12778354e-05]]
E: [[-125187.70253698  329637.65555466  -26906.5444175 ]
 [ 264567.03440838 -259977.21466638  161163.60006368]
 [ -42379.27679485  216198.8687726    1587

1583.3348217618186
En: [[ 2.78936478e-06  8.16450800e-04 -4.63521560e-01]
 [-8.19517564e-04  3.51220059e-06  5.33991662e-01]
 [ 4.62488238e-01 -5.34886867e-01  3.13847246e-06]]
E: [[-101618.19925513  338676.43154944   -4837.01088892]
 [  44482.72681837  368785.56761453  125936.4883827 ]
 [ -75190.76351956  374464.36093344   26084.06056919]]
Fn: [[-3.63602454e-06  2.40814482e-03 -4.55827826e-01]
 [-2.39869403e-03  2.39218238e-06  1.40904602e+00]
 [ 4.56089935e-01 -1.41452085e+00  1.00000000e+00]]
F: [[-1.95188146e-01  6.50529386e-01 -1.71610349e-01]
 [ 8.54423818e-02  7.08362988e-01  1.34529846e-02]
 [ 6.34963569e-04  1.39195253e-03 -8.26780932e-04]]
abs scale: 0.9129 | progress: 578 | len(src): 84 
10907.288420223507
En: [[-1.35948964e-06 -1.26990966e-03  2.17268916e-01]
 [ 1.26955971e-03 -5.25565159e-07 -6.72898659e-01]
 [-2.16535762e-01  6.73134943e-01  8.81335042e-07]]
E: [[-107649.02525389  337006.65973987  -10311.88785195]
 [ 242725.3892331  -284190.15660601  137007.8691588 ]
 [ -

3895.2221275266647
En: [[ 1.45309409e-05 -1.66081003e-03 -6.83719049e-01]
 [ 1.61195790e-03  2.52326321e-05  1.80348289e-01]
 [ 6.85095409e-01 -1.75047652e-01  1.44156581e-05]]
E: [[-140002.88726776  316546.45105278  -42274.50166596]
 [  99198.95669373  350364.35009466  167650.91807896]
 [ -94511.8836939   351354.87947771    4448.4069222 ]]
Fn: [[-6.69399718e-06  1.01213383e-02 -1.75753441e+00]
 [-1.01522732e-02 -2.27453405e-05  6.31797129e+00]
 [ 1.76785454e+00 -6.32251767e+00  1.00000000e+00]]
F: [[-2.68917421e-01  6.08022140e-01  2.32599187e-01]
 [ 1.90541267e-01  6.72979530e-01 -1.21141228e-01]
 [-1.46303923e-03  1.51992151e-04  2.30953407e-03]]
abs scale: 0.9053 | progress: 590 | len(src): 110 
58926.479286873844
En: [[-1.22188226e-05  1.35352037e-03  1.16181252e-01]
 [-1.35969648e-03  2.38245542e-05  6.97495557e-01]
 [-1.10876537e-01 -6.98358487e-01  3.22276306e-05]]
E: [[-101903.89719316  332359.25825242   -6665.46626836]
 [ 175371.76467546 -314262.19620586   72895.64600065]
 [ 

25064.935339077005
En: [[ 1.71827223e-06 -8.86062311e-04  1.24269155e-01]
 [ 9.01816852e-04  8.14350498e-06 -6.96100828e-01]
 [-1.27917085e-01  6.95439742e-01  4.87851420e-07]]
E: [[-139308.34916394  294759.17390137  -46818.64680437]
 [ 293887.92056849 -199262.02657491  200634.90359593]
 [ -47283.20804023  201279.45263573    8512.7989691 ]]
Fn: [[ 8.07261281e-07  5.27094187e-04 -9.74731033e-02]
 [-5.27338899e-04  1.07039035e-06  3.19566592e-01]
 [ 9.65110221e-02 -3.23492616e-01  1.00000000e+00]]
F: [[-0.26758335  0.56617316  0.35530716]
 [ 0.56449965 -0.38274232  0.12825191]
 [ 0.0007299   0.00145201 -0.0010909 ]]
abs scale: 0.9087 | progress: 602 | len(src): 150 
56035.68230243811
En: [[ 2.76492238e-07 -5.38101874e-04 -1.07694267e-01]
 [ 5.43514904e-04  1.36051819e-05 -6.98857390e-01]
 [ 1.07990661e-01  6.98811652e-01  1.43404313e-05]]
E: [[-136275.09296892  305389.39038115  -42238.4990264 ]
 [ 289932.70314156 -180738.67229201  201723.80909196]
 [ -45667.16121398  214696.7068726    12

26707.44321092694
En: [[ 4.66744211e-04 -1.29852451e-01 -3.35406969e-02]
 [ 1.30514368e-01 -8.20285365e-03  6.94175916e-01]
 [-3.44634457e-02  6.94095355e-01  8.69278469e-03]]
E: [[ 108615.08791168 -326766.02912757   13761.07918844]
 [-148033.18600041 -297728.62588108 -196391.87440699]
 [  56290.41115043 -347379.11490969  -35427.11210724]]
Fn: [[ 4.22298083e-07  6.14551820e-04 -1.08139720e-01]
 [-6.14586818e-04 -1.54596246e-07  3.72405117e-01]
 [ 1.06844926e-01 -3.74467390e-01  1.00000000e+00]]
F: [[ 2.08627764e-01 -6.27651896e-01  3.93025594e-01]
 [-2.84342011e-01 -5.71876878e-01 -1.06647090e-02]
 [-6.82811511e-03 -5.21925571e-04 -2.06434809e-03]]
abs scale: 0.9196 | progress: 614 | len(src): 162 
22850.233762849297
En: [[ 7.31119224e-06 -2.08721507e-03  1.84392358e-01]
 [ 2.09260917e-03  7.85191484e-06 -6.82638323e-01]
 [-1.87237744e-01  6.81863380e-01 -2.26928684e-06]]
E: [[ -97694.38712296  337339.52351893   -1560.60556055]
 [ 203558.09387356 -305338.03135766   98826.66589884]
 [ -

3890.499193790012
En: [[-5.13027382e-04  3.05397640e-01  4.79311357e-01]
 [-3.06986579e-01  1.23725586e-02 -4.24740946e-01]
 [ 4.66514203e-01 -4.29602552e-01 -2.75730049e-04]]
E: [[-103190.47768031  340381.56383154   -5717.94938849]
 [ 230007.09645556 -293968.30222162  123834.48952624]
 [ -32075.76246669  217132.16565282   24834.67451653]]
Fn: [[-1.11420198e-06 -8.16648941e-04  1.48393971e-01]
 [ 8.16521727e-04 -4.09272376e-07 -5.07352288e-01]
 [-1.49568193e-01  5.08390138e-01  1.00000000e+00]]
F: [[-1.98208177e-01  6.53804603e-01 -1.17774841e-01]
 [ 4.41797425e-01 -5.64654052e-01 -7.32113440e-02]
 [-1.54275744e-03 -2.06425763e-04  8.12412825e-04]]
abs scale: 0.8655 | progress: 626 | len(src): 179 
9032.80330210537
En: [[ 3.42478427e-06  1.97342157e-03 -4.35141277e-01]
 [-1.97237796e-03  1.78644334e-05  5.57358237e-01]
 [ 4.32490575e-01 -5.59417538e-01  2.55833532e-06]]
E: [[-117314.48267902  326542.90843307  -21042.93980369]
 [ 118599.95618221  349746.64636064  184010.75037498]
 [ -70

25553.09612804657
En: [[-4.45483189e-06  2.68393424e-03 -4.84163124e-01]
 [-2.68309492e-03  1.36902441e-04 -5.15343261e-01]
 [ 4.96135868e-01  5.03827522e-01  6.33309332e-06]]
E: [[ 131364.18007818 -310408.18624533   36813.90655031]
 [-331095.12811939  -24817.56745172 -285882.31746285]
 [  31660.11936981 -268182.695049    -37385.98848057]]
Fn: [[ 4.26882795e-07 -3.80663678e-04  6.97857863e-02]
 [ 3.80490048e-04  8.31218758e-07 -2.32958868e-01]
 [-7.16506310e-02  2.32810027e-01  1.00000000e+00]]
F: [[ 2.52324199e-01 -5.96231766e-01  2.75942829e-01]
 [-6.35967226e-01 -4.76695613e-02 -3.12974005e-01]
 [ 1.59298446e-03 -3.67341148e-03  5.25372811e-04]]
abs scale: 0.8344 | progress: 638 | len(src): 191 
5682.161460663716
En: [[ 7.00536029e-06  1.97013991e-03 -5.47998820e-01]
 [-1.95371313e-03  3.59251555e-05  4.46870779e-01]
 [ 5.40588315e-01 -4.55807387e-01 -2.14962626e-05]]
E: [[ 129023.29087336 -305198.76080172   36137.8021976 ]
 [-357769.10506683   -5222.86438074 -303497.48504972]
 [  2

11067.791093844091
En: [[-1.68892887e-06 -6.20038127e-04  2.42065270e-01]
 [ 6.11592758e-04  3.51439118e-05 -6.64382430e-01]
 [-2.41968053e-01  6.64417859e-01  3.36352589e-05]]
E: [[-78746.84026561 342340.917236    15651.87654318]
 [-45349.53455841 362301.97408221  48469.37949008]
 [-77390.9319109  376006.49076446  24833.53766322]]
Fn: [[ 7.73208150e-06 -2.65415489e-03  4.68908825e-01]
 [ 2.65041463e-03  7.40025998e-06 -1.59221935e+00]
 [-4.75285168e-01  1.59337693e+00  1.00000000e+00]]
F: [[-0.15125686  0.65756813  0.2291339 ]
 [-0.08710735  0.69590931 -0.01849785]
 [-0.00145546  0.00081294 -0.00087932]]
abs scale: 0.9031 | progress: 650 | len(src): 184 
90682.55711783557
En: [[-3.31420046e-07  2.63759560e-03 -6.99147530e-01]
 [-2.58909633e-03  5.93409780e-05  1.05763068e-01]
 [ 6.96276405e-01 -1.23257469e-01 -7.20441045e-05]]
E: [[-112945.09291957  329912.57660442  -16270.34044654]
 [ 319256.81401155 -194807.97485938  223118.45565023]
 [ -18932.85229115  232042.67019005   39706.93780

26231.310487277835
En: [[ 1.66210679e-07 -1.16599525e-03  1.80883154e-01]
 [ 1.17088051e-03 -1.19089664e-05 -6.83578760e-01]
 [-1.81224607e-01  6.83488313e-01 -1.29101895e-05]]
E: [[ -86787.81606871  342602.73906846    8902.95006643]
 [ 244926.57418031 -273215.12694474  141484.51496238]
 [ -14633.91358204  223980.94833652   41423.91944829]]
Fn: [[ 4.27677014e-06  2.57931689e-03 -4.57426328e-01]
 [-2.57944715e-03  5.19371295e-07  1.57485102e+00]
 [ 4.53259892e-01 -1.57514926e+00  1.00000000e+00]]
F: [[-1.66701959e-01  6.58071034e-01  2.03375490e-01]
 [ 4.70454744e-01 -5.24791371e-01  2.97108355e-02]
 [ 1.31805427e-02  6.53176959e-04  9.32445758e-04]]
abs scale: 0.8723 | progress: 662 | len(src): 199 
2564.1727176230706
En: [[ 9.67008237e-07 -1.09573878e-03  2.08550097e-01]
 [ 1.09205868e-03  9.01982019e-06 -6.75652025e-01]
 [-2.08939703e-01  6.75531647e-01  8.72519310e-06]]
E: [[ -66542.71207882  359323.96816495   29947.92081414]
 [ 141016.39136696 -337146.28281425   38390.68711668]
 [ 

19660.769957404176
En: [[ 7.84394932e-06 -3.37898503e-03  4.29527555e-01]
 [ 3.36472525e-03 -1.68484133e-04 -5.61689665e-01]
 [-4.19045325e-01  5.69551619e-01 -3.56546569e-05]]
E: [[-111398.3433061   337321.18421261  -13153.58183799]
 [ 321414.59641095 -168884.84277449  231015.34968831]
 [ -17105.01446084  244512.25467644   44235.48097699]]
Fn: [[ 1.71367248e-07  4.70401971e-04 -8.38419622e-02]
 [-4.70154446e-04 -2.84011143e-07  2.90713898e-01]
 [ 8.20292361e-02 -2.90506370e-01  1.00000000e+00]]
F: [[-2.13973838e-01  6.47926229e-01  2.03172535e-01]
 [ 6.17372869e-01 -3.24393855e-01 -8.17332794e-02]
 [ 8.03801847e-03 -6.61711691e-05  1.46447338e-03]]
abs scale: 0.7821 | progress: 674 | len(src): 136 
24356.26146169404
En: [[ 1.12541357e-06 -1.10231042e-03  2.21843968e-01]
 [ 1.09674714e-03  9.22366392e-06 -6.71404531e-01]
 [-2.22005973e-01  6.71350981e-01  9.81849021e-06]]
E: [[-102511.01192127  327417.03952144   -8358.29988003]
 [ 180930.11413179  311340.92810703  227525.91589244]
 [ -

11269.301295930898
En: [[ 1.36395348e-06 -1.12566484e-03  2.02776597e-01]
 [ 1.13004292e-03 -7.47635493e-06 -6.77407101e-01]
 [-2.03880691e-01  6.77075616e-01 -9.78988157e-06]]
E: [[ -92865.25966686  340865.35572361    3361.27835789]
 [ 230831.4120446  -281557.29542684  127511.74263069]
 [ -23149.64035732  220513.90484285   33390.68375177]]
Fn: [[-4.81306754e-07  1.30664860e-03 -2.32317753e-01]
 [-1.30587090e-03 -7.89592013e-07  7.96004970e-01]
 [ 2.31340327e-01 -7.97605274e-01  1.00000000e+00]]
F: [[-1.78375508e-01  6.54733870e-01  2.15574230e-01]
 [ 4.43380770e-01 -5.40815001e-01 -6.26174735e-02]
 [ 6.55284465e-03 -4.74758333e-04  1.45800210e-03]]
abs scale: 0.7720 | progress: 686 | len(src): 128 
2149.309168997439
En: [[ 5.12220950e-06 -1.02600803e-03  1.92625712e-01]
 [ 1.02426481e-03  1.23364325e-05 -6.80363345e-01]
 [-1.96078642e-01  6.79376271e-01  7.04556925e-06]]
E: [[ -73614.88485127  344195.91586242   20415.27250976]
 [ 163190.98281864 -328333.7851371    59160.33215837]
 [ -

16207.862928617713
En: [[ 7.89632637e-07 -1.11482721e-03  1.81699975e-01]
 [ 1.11544281e-03  3.48760492e-06 -6.83362183e-01]
 [-1.82387210e-01  6.83179086e-01  2.03403893e-06]]
E: [[ -86072.44134296  333519.7160914     7363.73652449]
 [ 260125.0616299  -257278.77418025  158061.27116737]
 [ -10397.83600887  220124.4123846    44086.71176728]]
Fn: [[ 2.25868603e-06 -4.92900502e-03  1.03563975e+00]
 [ 4.92700555e-03  2.50840284e-05 -3.30883428e+00]
 [-1.04136587e+00  3.31356486e+00  1.00000000e+00]]
F: [[-1.65327868e-01  6.40624372e-01  2.48270207e-01]
 [ 4.99647985e-01 -4.94180839e-01 -8.22470623e-02]
 [ 3.24639087e-04 -6.09313738e-04  1.07099425e-03]]
abs scale: 0.6234 | progress: 698 | len(src): 111 
301.91588784082387
En: [[ 7.27928324e-09 -1.13132381e-03  2.04286346e-01]
 [ 1.12886127e-03  7.88945111e-06 -6.76953328e-01]
 [-2.04276808e-01  6.76956211e-01  7.92862018e-06]]
E: [[-101546.76817091  339746.0104932    -4261.0903956 ]
 [ 220656.92395724  292346.78429572  256393.21869084]
 [ 

1313.5698037909606
En: [[-1.80078190e-06 -1.38951328e-03  1.03019309e-01]
 [ 1.38987230e-03 -5.54241190e-06 -6.99560642e-01]
 [-1.02099027e-01  6.99695545e-01 -3.68724865e-06]]
E: [[ -49063.96159841  348451.95994372   41875.49106343]
 [-110492.85419916  337480.15233627  -12629.79863997]
 [ -67911.78248232  375221.38315322   32357.41510558]]
Fn: [[-2.55544323e-06 -1.17129018e-03  2.80221004e-01]
 [ 1.17021054e-03  1.50531223e-05 -9.79979838e-01]
 [-2.80673657e-01  9.82179030e-01  1.00000000e+00]]
F: [[-9.42420135e-02  6.69306213e-01 -2.09704181e-01]
 [-2.12234575e-01  6.48231574e-01 -1.83865139e-01]
 [ 1.07844643e-02 -1.06267762e-03  5.29668893e-04]]
abs scale: 0.5016 | progress: 710 | len(src): 132 
1217.8884333637543
En: [[-1.25088953e-06 -1.20991765e-03  9.23986449e-02]
 [ 1.21228374e-03 -2.32511566e-06 -7.01042810e-01]
 [-9.18408935e-02  7.01116100e-01 -1.64900366e-06]]
E: [[-49155.84989608 337902.61500359  39229.47934433]
 [-88741.27196382 354174.22995579   9818.64127969]
 [-62781.

9588.59017428718
En: [[ 8.01510842e-07 -1.06798242e-03  1.89129983e-01]
 [ 1.06730831e-03  3.60007637e-07 -6.81343313e-01]
 [-1.89510283e-01  6.81237633e-01 -3.04122846e-08]]
E: [[ -84502.58129419  350242.68559139   12429.38541412]
 [ 244058.49103179 -276403.08510395  139917.07610937]
 [ -12914.36437952  229670.85727774   44024.82430813]]
Fn: [[ 3.00153071e-06 -4.47679623e-03  9.08055521e-01]
 [ 4.47567440e-03  1.41217473e-05 -2.96140319e+00]
 [-9.11194875e-01  2.95811146e+00  1.00000000e+00]]
F: [[-1.62312482e-01  6.72745837e-01 -1.21480381e-01]
 [ 4.68787331e-01 -5.30914798e-01 -6.78018903e-02]
 [ 8.92618722e-03 -2.40617430e-04  1.13936282e-03]]
abs scale: 0.3695 | progress: 722 | len(src): 142 
12895.389713287812
En: [[ 1.07935909e-06 -9.89556810e-04  1.45019106e-01]
 [ 9.90017210e-04  3.74494636e-07 -6.92075487e-01]
 [-1.45817658e-01  6.91907675e-01 -8.30560058e-07]]
E: [[ -77883.78203386  323425.90480951   11469.26035467]
 [ 219215.96024725 -284637.81058857  117123.88199469]
 [ -1

24094.424675206858
En: [[-8.81749918e-07 -1.14920729e-03  2.73825810e-01]
 [ 1.15000682e-03 -3.48967487e-07 -6.51934125e-01]
 [-2.73532818e-01  6.52057112e-01 -1.97502397e-07]]
E: [[-102152.24021035  335970.99470827   -5970.87552413]
 [ 353125.14697348  -82993.30831512  278363.11682138]
 [  -1703.54356219  263948.69211214   61641.02395693]]
Fn: [[ 1.84895094e-06  1.20925102e-03 -2.23854891e-01]
 [-1.20787126e-03  1.02575534e-05  6.16058299e-01]
 [ 2.21270506e-01 -6.19532566e-01  1.00000000e+00]]
F: [[-1.96213932e-01  6.45332786e-01 -2.19535959e-01]
 [ 6.78282466e-01 -1.59413472e-01 -1.06621657e-01]
 [-8.01016659e-04  7.93646188e-04  6.65842445e-04]]
abs scale: 0.2809 | progress: 734 | len(src): 155 
77259.64601126066
En: [[ 8.15696075e-06 -1.90931048e-03 -7.05482949e-01]
 [ 1.93551813e-03 -5.15421104e-05  4.78557710e-02]
 [ 7.04032207e-01 -6.58398689e-02  5.47265970e-05]]
E: [[ -77072.71360734  330333.2549865    13829.73446623]
 [ 268682.62242189 -246346.16280137  167888.31946713]
 [  

20699.59902053728
En: [[-2.92184791e-04  6.46068462e-02  7.84865699e-02]
 [-6.38967638e-02  2.00404174e-03 -6.99846228e-01]
 [ 8.02836147e-02 -6.99531552e-01 -2.07878267e-03]]
E: [[ 114425.80743854 -312032.05216529   22141.29512358]
 [-363657.0283833   -34784.44864479 -315515.06018411]
 [   9549.27781891 -271938.90420519  -56880.09517971]]
Fn: [[ 1.38417847e-07  4.48731275e-04 -8.56678373e-02]
 [-4.47486155e-04  1.33959867e-06  2.26264198e-01]
 [ 8.60876348e-02 -2.33692294e-01  1.00000000e+00]]
F: [[ 2.19788988e-01 -5.99350886e-01  3.12038462e-01]
 [-6.98512094e-01 -6.68139378e-02  5.21379920e-02]
 [ 8.08376198e-04  9.58288107e-04 -3.51577047e-04]]
abs scale: 0.3144 | progress: 746 | len(src): 131 
533.5575179964944
En: [[ 3.16480804e-06 -1.66587825e-03  2.11926651e-02]
 [ 1.64975274e-03  3.95821004e-05  7.06787204e-01]
 [-1.96319620e-02 -7.06832233e-01  3.54259799e-05]]
E: [[-106402.79746102  321449.09903108  -12681.76186809]
 [ 350175.72328954 -110077.66943522  269496.47888308]
 [  -

51605.612115333475
En: [[ 7.18705869e-07  7.97287389e-04 -1.58870142e-01]
 [-7.82895287e-04  3.52889881e-06  6.89028058e-01]
 [ 1.55400927e-01 -6.89818756e-01 -3.70396207e-06]]
E: [[-107241.20698515  331396.39850072  -11066.26743114]
 [ 371427.17987814  -18927.78592176  309293.42960704]
 [  -1617.91718561  275431.26436843   64746.31631538]]
Fn: [[ 4.35580225e-07 -1.91392533e-04  3.81082811e-02]
 [ 1.92177263e-04  9.15535785e-09 -1.02452045e-01]
 [-3.88395854e-02  9.83681471e-02  1.00000000e+00]]
F: [[-2.05988814e-01  6.36545906e-01  1.95830933e-01]
 [ 7.13436995e-01 -3.63564743e-02  6.09307517e-02]
 [-3.59063665e-04  5.34281559e-05 -1.15710283e-03]]
abs scale: 0.2689 | progress: 758 | len(src): 134 
57679.908672647485
En: [[ 5.29876460e-07 -4.48338874e-04  9.87298033e-02]
 [ 4.35309912e-04  2.05477127e-05 -7.00180143e-01]
 [-9.73440646e-02  7.00374139e-01  2.28261657e-05]]
E: [[ -94838.42021125  352810.67391643    4301.75221372]
 [ 308723.71494967 -192064.42867312  214776.0374724 ]
 [ 

1314.5203234432356
En: [[ 1.36405924e-06 -9.66374410e-04  6.13884301e-02]
 [ 9.70743981e-04  2.22838580e-06 -7.04436313e-01]
 [-6.26629425e-02  7.04324088e-01  8.74038586e-08]]
E: [[-67610.90076163 355941.43226755  28249.06482759]
 [-65349.22992241 357792.6973586   30435.64622024]
 [-72769.52336371 386415.76914914  31159.56922288]]
Fn: [[ 5.28439112e-06 -4.49026270e-02  7.74054992e+00]
 [ 4.49167034e-02 -4.13564019e-05 -2.51958663e+01]
 [-7.76367938e+00  2.52549101e+01  1.00000000e+00]]
F: [[-1.29866958e-01  6.83691984e-01  1.33914791e-01]
 [-1.25522742e-01  6.87247893e-01 -9.83485453e-02]
 [ 5.32947164e-03  4.53524429e-04 -4.96392655e-05]]
abs scale: 0.2497 | progress: 770 | len(src): 137 
925.9967431891419
En: [[ 3.15729518e-06 -1.10809290e-03  4.74042570e-02]
 [ 1.11488202e-03  6.08471808e-06 -7.05515126e-01]
 [-4.97120773e-02  7.05356280e-01  1.96957252e-06]]
E: [[-115153.28325194  333013.84891878  -17351.40661366]
 [ 200522.52163344  298596.28350633  241036.7112632 ]
 [ -49242.866

77366.23091674689
En: [[-7.37175256e-06 -4.35083151e-04  3.17652606e-01]
 [ 4.23459502e-04  1.52501988e-05  6.31740966e-01]
 [-3.14992200e-01 -6.33071654e-01  4.26668756e-06]]
E: [[-131875.48675109  262017.94558819  -48336.03048943]
 [ 364593.94773884  -50978.17279295  295744.58982675]
 [ -24077.42072308  209139.82861858   30004.74545382]]
Fn: [[ 1.46881478e-06  1.95798023e-04 -3.92600780e-02]
 [-1.94843953e-04  1.93788384e-06  7.15646018e-02]
 [ 3.74449289e-02 -7.49804314e-02  1.00000000e+00]]
F: [[-2.53306317e-01  5.03283835e-01  4.20292276e-01]
 [ 7.00311728e-01 -9.79188287e-02 -7.48715139e-02]
 [-1.60571540e-02 -2.73425826e-03 -1.66173717e-04]]
abs scale: 0.1218 | progress: 782 | len(src): 169 
85618.80659300767
En: [[-1.10345839e-04 -9.17225375e-02  1.57399977e-01]
 [ 9.10034212e-02 -9.21227320e-04  6.83303448e-01]
 [ 1.57478228e-01  6.83246410e-01  1.04380652e-03]]
E: [[ 145091.80414304 -266281.33584603   59071.86199513]
 [-362659.6878563    61191.52453214 -291689.29397634]
 [  3

19447.442646661802
En: [[ 6.80378795e-06 -1.31291803e-02  3.56372863e-01]
 [ 1.31982212e-02  6.20482364e-06  6.10593683e-01]
 [-3.57458730e-01 -6.09959361e-01  5.98805665e-05]]
E: [[-154448.21106252  275446.93848521  -64229.08005002]
 [ 209333.40176425  292442.22544164  247012.32595656]
 [ -80330.09308883  302758.75820905    4914.3094491 ]]
Fn: [[-1.95469852e-06  1.99814272e-03 -2.59563075e-01]
 [-1.99268188e-03  2.08759796e-05 -5.94847153e-01]
 [ 2.58254339e-01  5.84379951e-01  1.00000000e+00]]
F: [[-2.96663986e-01  5.29078233e-01  3.64059857e-01]
 [ 4.02087411e-01  5.61722765e-01  1.49390649e-01]
 [ 7.10404950e-05  1.54932873e-03 -6.33821747e-04]]
abs scale: 0.0556 | progress: 794 | len(src): 266 
85986.00399730714
En: [[-2.50014844e-06  7.54483097e-04 -1.51471514e-01]
 [-7.58353602e-04 -6.59744395e-06  6.90692263e-01]
 [ 1.54675009e-01 -6.89981938e-01 -2.07707015e-06]]
E: [[-125009.63713284  320197.59728813  -28712.07719758]
 [  -3725.45955305  346164.90191962   79614.79273995]
 [-1

## Analysing the performance of our algorithm:

- Our algorithm works pretty well on straight line trajectories, the prediction is very accurate and error rate is less. 
- Our algorithm is a little less efficient on curved trajectories; it is not able to detect the curves in the trajectory with complete accuracy. 
- Once a mistake is made in the curved trajectories, it getrs compounded with each new observation because of the cumulative effect of the updates. 
- Rotations are not caputured well because in the RANSAC loop, while trying to estimate a better fundamental matrix, we try to use far-apart points. However this is counter-intuitive to finding rotations in the image, because far apart points don't have much of an observable rotation between frames. 

## Other ways of computing the absolute scale
2 possible methods:
- Use a second sensor, whose data is given as part of the dataset.
- Detect known objects within the scene, via corner detection. Then use these known values to estimate distance. For example, assuming the length of a car is normally around 9 feet. Observing cars in the image, and their motion across images can give you the scaling factor.